// «Kadrlar qo'nimsizligi» (/turnover) — the page's words in the four platform
// languages, beside the page (the leaders-KPI page's pattern, workerConcernsText).
// `fill(s, {n: 3})` puts the numbers in. The Excel file receives `xl` in the
// viewer's language, so the page and the file name every column one way.

export const fill = (s, vars) =>
  String(s ?? "").replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? `{${k}}`));

const uz = {
  title: "Kadrlar qo'nimsizligi",
  tabLeaders: "Liderlar", tabCells: "Yacheykalar", tabLeft: "Ketganlar",
  search: "Lider, yacheyka yoki ism",
  fShift: "Smena", fBrigadir: "Brigadir", shiftN: "{n}-smena", all: "Hammasi",
  excel: "Excel", refresh: "Verifix'dan yangilash", rulesBtn: "Qanday hisoblanadi?",
  close: "Oyni yopish", reopen: "Qayta ochish", cancel: "Bekor qilish", done: "Yopish",
  retry: "Qayta urinish",

  stOpen: "Oy davom etmoqda", stClosing: "Yopilishi kutilmoqda", stClosed: "Yopilgan",
  lineOpen: "Hozirgacha: {from} – {asOf}. Oy tugaguncha raqamlar o'zgaradi; {closeAt} da avtomatik yopiladi.",
  lineClosing: "Oy tugadi. Ishlayotganlar ro'yxati {rosterAt} da olindi. Kechikkan buyruqlar uchun ochiq — {closeAt} da avtomatik yopiladi.",
  lineClosingApprox: "Oy tugadi, lekin oy oxirida ro'yxat olinmadi — ishlayotganlar hozirgi bo'limlari bo'yicha taxminiy. {closeAt} da avtomatik yopiladi.",
  lineReopened: "{by} qayta ochgan ({at}). Admin yopmaguncha ochiq turadi.",
  lineClosed: "{at} da yopilgan ({by}). Bu oyning raqamlari endi o'zgarmaydi.",
  bySystem: "avtomatik",
  before: "Eng erta hisoblanadigan oy — 2025-yil yanvar.",
  beforeTitle: "Bu oy hisoblanmaydi",
  future: "Bu oy hali boshlanmagan.",
  stSaved: "Saqlangan hisob",
  lineSaved: "{at} da Verifix'ning o'sha kungi ma'lumotidan hisoblangan ({by}). «Yangilash» bugungi ma'lumot bilan qayta hisoblaydi.",
  compute: "Hisoblash", update: "Yangilash", computing: "Hisoblanmoqda…",
  pastTitle: "{month} hali hisoblanmagan",
  pastMsg: "2026-yil oktyabrgacha bo'lgan oylar o'zi hisoblanmaydi. «Hisoblash» Verifix'ni hozir o'qib, oyni hisoblaydi va saqlaydi — keyin tugma «Yangilash»ga aylanadi. Verifix o'tmishdagi bo'limlarni saqlamaydi, shuning uchun ishlayotganlar hozirgi bo'limlari bo'yicha sanaladi: natija taxminiy.",
  pastNoAdmin: "Oyni admin hisoblaydi.",
  nPastApprox: "Bu o'tgan oy bugungi Verifix ma'lumotidan hisoblangan: ishlayotganlar hozirgi bo'limlari bo'yicha, liderlar — /cells'ning hozirgi holati bo'yicha. O'shandan beri bo'lim almashtirganlar boshqa yacheykada sanalgan bo'lishi mumkin.",
  nRehired: "{n} kishi ketgandan keyin qayta ishga kirgan — ular ishdan bo'shatish buyrug'idan olindi, yacheykasi hozirgi bo'limi bo'yicha (≈).",
  approxHint: "Keyin qayta ishga kirgan: yacheyka hozirgi bo'limi bo'yicha",
  tComputeStarted: "{month} hisoblanmoqda — bir necha daqiqa", tComputed: "{month} hisoblandi va saqlandi",

  readAt: "Verifix: {at}", readNever: "Verifix hali o'qilmagan", readRunning: "Verifix o'qilmoqda…",
  readFailed: "Oxirgi o'qish bo'lmadi: {e}",
  readStale: "Verifix 30 soatdan beri o'qilmagan — raqamlar eskirgan bo'lishi mumkin.",
  notConfTitle: "Verifix ulanmagan",
  notConfMsg: "Admin panel → Vositalar → Verifix kartasida login va parolni kiriting.",
  noReadTitle: "Verifix hali o'qilmagan",
  noReadMsg: "Har kecha 23:40 da o'qiladi. Hozir o'qish bir necha daqiqa oladi.",
  readNow: "Hozir o'qish",

  kLeft: "Ketganlar", kLeftSub: "{n} tasi liderlarga hisoblandi",
  kWorking: "Oy oxirida ishlayotganlar", kWorkingOpen: "Hozir ishlayotganlar", kWorkingSub: "{n} ta yacheykada",
  kRate: "Qo'nimsizlik (yillik)", kRateSub: "{left} ÷ {working} × 12",
  kLeaders: "Baholangan liderlar", kLeadersSub: "{n} tasining yacheykasida hech kim yo'q",
  kLeadersAll: "hammasi baholandi",

  formula: "Qo'nimsizlik = ketganlar ÷ ishlayotganlar × 12",
  formulaHere: "Hozirgi tanlovda",
  smallTeam: "Kichik jamoada bitta ketgan ham katta foiz beradi: 12 kishilik yacheykada 1 kishi = 100%.",

  nTitle: "Hech kimning baliga ta'sir qilmaganlar",
  nNoLeader: "{n} kishi lideri yo'q yacheykalardan ketgan.",
  nUnreg: "{codes} — bu kodlar /cells ro'yxatida yo'q: {w} ishlayotgan va {l} ketgan hisobga kirmadi. Yacheykani /cells'ga qo'shib, lider biriktirsangiz, keyingi hisobda kiradi.",
  nOther: "{n} kishi yacheyka bo'lmagan bo'limlardan ketgan (xavfsizlik, IT, haydovchilar va h.k.) — bu KPI'ga kirmaydi.",
  nNoPeople: "{n} liderning yacheykalarida Verifix'da hech kim ishlamayapti — yacheyka kodi Verifix'dagi bo'lim kodiga mos kelmayotgan bo'lishi mumkin.",
  nReasons: "Ketish sabablari Verifix'dan kelmadi: API rolida «Увольнения» formasi ochilmagan. Hisobga ta'sir qilmaydi.",
  nRosterLate: "Ro'yxat oy tugaganidan {n} kun keyin olindi — shu kunlardagi bo'lim o'zgarishlari hisobga kirgan.",
  nDropped: "{n} kishi ro'yxat olingandan keyin shu oy sanasi bilan bo'shatilgan — ishlayotganlardan chiqarildi.",
  nLate: "Oy yopilgandan keyin Verifix'da {added} ta yangi ketish va {gone} ta bekor qilingan ketish paydo bo'ldi — hisobga kiritilmagan. Qo'shish uchun oyni qayta oching.",

  colN: "№", colLeader: "Lider", colBrigadir: "Brigadir", colCells: "Yacheykalar", colCell: "Yacheyka",
  colShift: "Smena", colWorking: "Ishlayotgan", colLeft: "Ketgan", colRate: "Qo'nimsizlik", colScore: "Ball",
  colPoints: "KPI", colName: "F.I.Sh.", colJob: "Lavozim", colHired: "Kirgan", colLeftOn: "Ketgan sana",
  colTenure: "Ishlagan", colReason: "Sabab", colCounted: "Kimga hisoblandi",
  hWorking: "Oy oxirida ishlayotganlar (hozirgi oyda — hozir)",
  hLeft: "Oy ichida ishdan bo'shatilganlar",
  hRate: "Ketgan ÷ ishlayotgan × 12, bir xonali kasrgacha",
  hScore: "Ball shkalasi bo'yicha 1–5",
  hPoints: "Ball × 20% — Liderlar KPI'dagi ulushi (eng ko'pi 1,0)",
  countedLeader: "Liderga", countedNoLeader: "Lider yo'q", countedNoCell: "/cells'da yo'q",
  noLeader: "Lider yo'q", acting: "Lider o'rnida", archived: "Arxivda",
  noRateHint: "Ishlayotgan yo'q — hisoblab bo'lmaydi",
  tLeaders: "Liderlar KPI", tCells: "Yacheykalar", tLeft: "Ketganlar",
  nLeaders: "{n} lider", nCells: "{n} yacheyka", nPeople: "{n} kishi",
  nothing: "Hech narsa topilmadi", noneLeft: "Bu oyda hech kim ketmagan",
  days: "{n} kun", months: "{n} oy", years: "{y} yil {m} oy",

  bandsTitle: "Ball shkalasi", kpiLine: "KPI bali = ball × {w}%",
  provisional: "Oy tugamagan — ball oy oxirigacha o'zgaradi",

  exCalc: "Hisob", exCells: "Yacheykalar", exTotal: "Jami",
  exWorkingLeft: "{w} ishlayotgan · {l} ketgan",
  exNoWorking: "Ishlayotgan yo'q — qo'nimsizlikni hisoblab bo'lmaydi, ball qo'yilmaydi.",
  scoreN: "{n} ball",
  exScore: "{rate} → {score} ball", exPoints: "KPI: {score} × {w}% = {p}",
  exLeftList: "Ketganlar", exWorkingList: "Ishlayotganlar", exNone: "Hech kim",
  exLoadFail: "Ro'yxat yuklanmadi", exWorkingAt: "{date} holatiga",
  exWhyLeft: "Verifix'da shu oy sanasi bilan ishdan bo'shatilgan, ketgan paytidagi bo'limi shu yacheyka.",
  exWhyWorking: "Shu kuni ishlagan va bo'limi shu yacheyka. Shu oyda ketganlar bu ro'yxatga kirmaydi.",

  rulesTitle: "Qanday hisoblanadi",
  rules: [
    ["Ketgan", "Verifix'da ishdan bo'shatilgan sanasi («Дата увольнения») shu oyga to'g'ri kelgan har bir xodim — sababidan qat'i nazar: o'zi ketganmi yoki bo'shatilganmi."],
    ["Ishlayotgan", "Oyning oxirgi kunida ishlagan xodim (shu kungacha ishga kirgan va bo'shamagan). Shu oyda ketganlar bu songa kirmaydi. Joriy oyda — oxirgi o'qish kunidagi holat."],
    ["Yacheyka", "Xodimning Verifix'dagi bo'limi («отдел») kodi: ketgan — ketgan paytidagi bo'limi, ishlayotgan — oy oxiridagi bo'limi. Faqat /cells ro'yxatidagi yacheykalar hisobga kiradi."],
    ["Lider", "Yacheykaning /cells'dagi lideri (oy oxiridagi holat). Bir nechta yacheykasi bo'lsa, hammasi qo'shib hisoblanadi: barcha ketganlar ÷ barcha ishlayotganlar × 12."],
    ["× 12", "Bir oyni yillik ko'rsatkichga aylantiradi: har oy shunday ketsa, bir yilda jamoaning necha foizi almashadi."],
    ["Ball", "Foiz bir xonali kasrgacha yaxlitlanib, shkala bo'yicha baholanadi. Ishlayotgan bo'lmasa, ball qo'yilmaydi."],
    ["KPI", "Ball × 20% — Liderlar KPI'ning 5 ko'rsatkichidan 2-si (eng ko'pi 1,0)."],
    ["Oy yopilishi", "Oy tugagach, kechikib kiritilgan buyruqlar uchun keyingi oyning 5-sanasi 09:00 gacha ochiq turadi, keyin avtomatik yopiladi va raqamlari qotadi. Admin oldinroq yopishi yoki qayta ochishi mumkin."],
    ["Manba", "Verifix API: har kecha 23:40 da va «Verifix'dan yangilash» tugmasida o'qiladi. Verifix faqat bugungi holatni biladi, shuning uchun oy oxiridagi ro'yxat o'sha kuni saqlab qo'yiladi. Hisob 2026-yil oktyabrdan boshlangan."],
    ["O'tgan oylar", "2026-yil oktyabrgacha bo'lgan oylar (2025-yil yanvardan) «Hisoblash» tugmasi bilan hisoblanadi va saqlanadi; «Yangilash» qayta hisoblaydi. Ketganlar — Verifix'dagi bo'shatish sanasi bo'yicha (keyin qayta ishga kirganlar bo'shatish buyrug'idan); ishlayotganlar — hozirgi bo'limlari bo'yicha, chunki Verifix o'tmishdagi bo'limni saqlamaydi. Shuning uchun bunday oy taxminiy."],
  ],

  closeTitle: "{month} yopilsinmi?",
  closeMsg: "Yopilgandan keyin bu oyning raqamlari o'zgarmaydi. Keyin kiritilgan buyruqlar alohida ko'rsatiladi.",
  reopenTitle: "{month} qayta ochilsinmi?",
  reopenMsg: "Ketganlar yana Verifix'dan jonli o'qiladi. Ishlayotganlar ro'yxati oy oxirida olingan holicha qoladi. Siz yopmaguncha oy ochiq turadi.",

  tReadStarted: "Verifix o'qilmoqda — bir necha daqiqa", tReadBusy: "O'qish allaqachon ketmoqda",
  tReadDone: "Verifix o'qildi", tReadFailed: "Verifix o'qilmadi: {e}",
  tClosed: "{month} yopildi", tReopened: "{month} qayta ochildi", tFailed: "Bajarilmadi: {e}",
  tExportDl: "Excel yuklab olindi", tExportTg: "Excel Telegram'ga yuborildi", tExportFail: "Excel tayyorlanmadi: {e}",
  loadFailed: "Ma'lumot yuklanmadi", loadFailedMsg: "Server javob bermadi. Qayta urinib ko'ring.",

  mMonth: "Oy", mState: "Holat", mList: "Ro'yxat olingan", mRead: "Verifix o'qilgan", mScope: "Tanlov",
  mScopeAll: "Butun zavod",
  xl: {
    sheetSummary: "Umumiy", sheetLeaders: "Liderlar", sheetCells: "Yacheykalar", sheetLeft: "Ketganlar",
    sheetWorking: "Ishlayotganlar", left: "Ketganlar", working: "Oy oxirida ishlayotganlar",
    rate: "Qo'nimsizlik (yillik)", leaders: "Baholangan liderlar", formula: "Qanday hisoblanadi",
    bands: "Ball shkalasi", bandRate: "Qo'nimsizlik", bandScore: "Ball", bandPoints: "KPI bali",
    nobody: "Hech kimga hisoblanmaganlar", colN: "№", colLeader: "Lider", colBrigadir: "Brigadir",
    colCells: "Yacheykalar", colCell: "Yacheyka", colShift: "Smena", colWorking: "Ishlayotganlar",
    colLeft: "Ketganlar", colRate: "Qo'nimsizlik, %", colScore: "Ball", colPoints: "KPI bali",
    colName: "F.I.Sh.", colJob: "Lavozim", colHired: "Ishga kirgan", colLeftOn: "Ketgan sana",
    colDays: "Ishlagan kuni", colReason: "Sabab", colNote: "Izoh", colCounted: "Kimga hisoblandi",
    countedLeader: "Liderga", countedNoLeader: "Lidersiz yacheyka", countedNoCell: "Yacheyka /cells'da yo'q",
    noLeader: "Lider yo'q", nobodyNoLeader: "Lidersiz yacheykalardan ketganlar",
    nobodyNoCell: "/cells'da yo'q kod", nobodyOther: "Yacheyka bo'lmagan bo'limlardan ketganlar (KPI'ga kirmaydi)",
  },
};

const uz_cyrl = {
  title: "Кадрлар қўнимсизлиги",
  tabLeaders: "Лидерлар", tabCells: "Ячейкалар", tabLeft: "Кетганлар",
  search: "Лидер, ячейка ёки исм",
  fShift: "Смена", fBrigadir: "Бригадир", shiftN: "{n}-смена", all: "Ҳаммаси",
  excel: "Excel", refresh: "Verifix'дан янгилаш", rulesBtn: "Қандай ҳисобланади?",
  close: "Ойни ёпиш", reopen: "Қайта очиш", cancel: "Бекор қилиш", done: "Ёпиш",
  retry: "Қайта уриниш",

  stOpen: "Ой давом этмоқда", stClosing: "Ёпилиши кутилмоқда", stClosed: "Ёпилган",
  lineOpen: "Ҳозиргача: {from} – {asOf}. Ой тугагунча рақамлар ўзгаради; {closeAt} да автоматик ёпилади.",
  lineClosing: "Ой тугади. Ишлаётганлар рўйхати {rosterAt} да олинди. Кечиккан буйруқлар учун очиқ — {closeAt} да автоматик ёпилади.",
  lineClosingApprox: "Ой тугади, лекин ой охирида рўйхат олинмади — ишлаётганлар ҳозирги бўлимлари бўйича тахминий. {closeAt} да автоматик ёпилади.",
  lineReopened: "{by} қайта очган ({at}). Админ ёпмагунча очиқ туради.",
  lineClosed: "{at} да ёпилган ({by}). Бу ойнинг рақамлари энди ўзгармайди.",
  bySystem: "автоматик",
  before: "Энг эрта ҳисобланадиган ой — 2025 йил январь.",
  beforeTitle: "Бу ой ҳисобланмайди",
  future: "Бу ой ҳали бошланмаган.",
  stSaved: "Сақланган ҳисоб",
  lineSaved: "{at} да Verifix'нинг ўша кунги маълумотидан ҳисобланган ({by}). «Янгилаш» бугунги маълумот билан қайта ҳисоблайди.",
  compute: "Ҳисоблаш", update: "Янгилаш", computing: "Ҳисобланмоқда…",
  pastTitle: "{month} ҳали ҳисобланмаган",
  pastMsg: "2026 йил октябргача бўлган ойлар ўзи ҳисобланмайди. «Ҳисоблаш» Verifix'ни ҳозир ўқиб, ойни ҳисоблайди ва сақлайди — кейин тугма «Янгилаш»га айланади. Verifix ўтмишдаги бўлимларни сақламайди, шунинг учун ишлаётганлар ҳозирги бўлимлари бўйича саналади: натижа тахминий.",
  pastNoAdmin: "Ойни админ ҳисоблайди.",
  nPastApprox: "Бу ўтган ой бугунги Verifix маълумотидан ҳисобланган: ишлаётганлар ҳозирги бўлимлари бўйича, лидерлар — /cells'нинг ҳозирги ҳолати бўйича. Ўшандан бери бўлим алмаштирганлар бошқа ячейкада саналган бўлиши мумкин.",
  nRehired: "{n} киши кетгандан кейин қайта ишга кирган — улар ишдан бўшатиш буйруғидан олинди, ячейкаси ҳозирги бўлими бўйича (≈).",
  approxHint: "Кейин қайта ишга кирган: ячейка ҳозирги бўлими бўйича",
  tComputeStarted: "{month} ҳисобланмоқда — бир неча дақиқа", tComputed: "{month} ҳисобланди ва сақланди",

  readAt: "Verifix: {at}", readNever: "Verifix ҳали ўқилмаган", readRunning: "Verifix ўқилмоқда…",
  readFailed: "Охирги ўқиш бўлмади: {e}",
  readStale: "Verifix 30 соатдан бери ўқилмаган — рақамлар эскирган бўлиши мумкин.",
  notConfTitle: "Verifix уланмаган",
  notConfMsg: "Админ панел → Воситалар → Verifix картасида логин ва паролни киритинг.",
  noReadTitle: "Verifix ҳали ўқилмаган",
  noReadMsg: "Ҳар кеча 23:40 да ўқилади. Ҳозир ўқиш бир неча дақиқа олади.",
  readNow: "Ҳозир ўқиш",

  kLeft: "Кетганлар", kLeftSub: "{n} таси лидерларга ҳисобланди",
  kWorking: "Ой охирида ишлаётганлар", kWorkingOpen: "Ҳозир ишлаётганлар", kWorkingSub: "{n} та ячейкада",
  kRate: "Қўнимсизлик (йиллик)", kRateSub: "{left} ÷ {working} × 12",
  kLeaders: "Баҳоланган лидерлар", kLeadersSub: "{n} тасининг ячейкасида ҳеч ким йўқ",
  kLeadersAll: "ҳаммаси баҳоланди",

  formula: "Қўнимсизлик = кетганлар ÷ ишлаётганлар × 12",
  formulaHere: "Ҳозирги танловда",
  smallTeam: "Кичик жамоада битта кетган ҳам катта фоиз беради: 12 кишилик ячейкада 1 киши = 100%.",

  nTitle: "Ҳеч кимнинг балига таъсир қилмаганлар",
  nNoLeader: "{n} киши лидери йўқ ячейкалардан кетган.",
  nUnreg: "{codes} — бу кодлар /cells рўйхатида йўқ: {w} ишлаётган ва {l} кетган ҳисобга кирмади. Ячейкани /cells'га қўшиб, лидер бириктирсангиз, кейинги ҳисобда киради.",
  nOther: "{n} киши ячейка бўлмаган бўлимлардан кетган (хавфсизлик, IT, ҳайдовчилар ва ҳ.к.) — бу KPI'га кирмайди.",
  nNoPeople: "{n} лидернинг ячейкаларида Verifix'да ҳеч ким ишламаяпти — ячейка коди Verifix'даги бўлим кодига мос келмаётган бўлиши мумкин.",
  nReasons: "Кетиш сабаблари Verifix'дан келмади: API ролида «Увольнения» формаси очилмаган. Ҳисобга таъсир қилмайди.",
  nRosterLate: "Рўйхат ой тугаганидан {n} кун кейин олинди — шу кунлардаги бўлим ўзгаришлари ҳисобга кирган.",
  nDropped: "{n} киши рўйхат олингандан кейин шу ой санаси билан бўшатилган — ишлаётганлардан чиқарилди.",
  nLate: "Ой ёпилгандан кейин Verifix'да {added} та янги кетиш ва {gone} та бекор қилинган кетиш пайдо бўлди — ҳисобга киритилмаган. Қўшиш учун ойни қайта очинг.",

  colN: "№", colLeader: "Лидер", colBrigadir: "Бригадир", colCells: "Ячейкалар", colCell: "Ячейка",
  colShift: "Смена", colWorking: "Ишлаётган", colLeft: "Кетган", colRate: "Қўнимсизлик", colScore: "Балл",
  colPoints: "KPI", colName: "Ф.И.Ш.", colJob: "Лавозим", colHired: "Кирган", colLeftOn: "Кетган сана",
  colTenure: "Ишлаган", colReason: "Сабаб", colCounted: "Кимга ҳисобланди",
  hWorking: "Ой охирида ишлаётганлар (жорий ойда — ҳозир)",
  hLeft: "Ой ичида ишдан бўшатилганлар",
  hRate: "Кетган ÷ ишлаётган × 12, бир хонали касргача",
  hScore: "Балл шкаласи бўйича 1–5",
  hPoints: "Балл × 20% — Лидерлар KPI'даги улуши (энг кўпи 1,0)",
  countedLeader: "Лидерга", countedNoLeader: "Лидер йўқ", countedNoCell: "/cells'да йўқ",
  noLeader: "Лидер йўқ", acting: "Лидер ўрнида", archived: "Архивда",
  noRateHint: "Ишлаётган йўқ — ҳисоблаб бўлмайди",
  tLeaders: "Лидерлар KPI", tCells: "Ячейкалар", tLeft: "Кетганлар",
  nLeaders: "{n} лидер", nCells: "{n} ячейка", nPeople: "{n} киши",
  nothing: "Ҳеч нарса топилмади", noneLeft: "Бу ойда ҳеч ким кетмаган",
  days: "{n} кун", months: "{n} ой", years: "{y} йил {m} ой",

  bandsTitle: "Балл шкаласи", kpiLine: "KPI балли = балл × {w}%",
  provisional: "Ой тугамаган — балл ой охиригача ўзгаради",

  exCalc: "Ҳисоб", exCells: "Ячейкалар", exTotal: "Жами",
  exWorkingLeft: "{w} ишлаётган · {l} кетган",
  exNoWorking: "Ишлаётган йўқ — қўнимсизликни ҳисоблаб бўлмайди, балл қўйилмайди.",
  scoreN: "{n} балл",
  exScore: "{rate} → {score} балл", exPoints: "KPI: {score} × {w}% = {p}",
  exLeftList: "Кетганлар", exWorkingList: "Ишлаётганлар", exNone: "Ҳеч ким",
  exLoadFail: "Рўйхат юкланмади", exWorkingAt: "{date} ҳолатига",
  exWhyLeft: "Verifix'да шу ой санаси билан ишдан бўшатилган, кетган пайтидаги бўлими шу ячейка.",
  exWhyWorking: "Шу куни ишлаган ва бўлими шу ячейка. Шу ойда кетганлар бу рўйхатга кирмайди.",

  rulesTitle: "Қандай ҳисобланади",
  rules: [
    ["Кетган", "Verifix'да ишдан бўшатилган санаси («Дата увольнения») шу ойга тўғри келган ҳар бир ходим — сабабидан қатъи назар: ўзи кетганми ёки бўшатилганми."],
    ["Ишлаётган", "Ойнинг охирги кунида ишлаган ходим (шу кунгача ишга кирган ва бўшамаган). Шу ойда кетганлар бу сонга кирмайди. Жорий ойда — охирги ўқиш кунидаги ҳолат."],
    ["Ячейка", "Ходимнинг Verifix'даги бўлими («отдел») коди: кетган — кетган пайтидаги бўлими, ишлаётган — ой охиридаги бўлими. Фақат /cells рўйхатидаги ячейкалар ҳисобга киради."],
    ["Лидер", "Ячейканинг /cells'даги лидери (ой охиридаги ҳолат). Бир нечта ячейкаси бўлса, ҳаммаси қўшиб ҳисобланади: барча кетганлар ÷ барча ишлаётганлар × 12."],
    ["× 12", "Бир ойни йиллик кўрсаткичга айлантиради: ҳар ой шундай кетса, бир йилда жамоанинг неча фоизи алмашади."],
    ["Балл", "Фоиз бир хонали касргача яхлитланиб, шкала бўйича баҳоланади. Ишлаётган бўлмаса, балл қўйилмайди."],
    ["KPI", "Балл × 20% — Лидерлар KPI'нинг 5 кўрсаткичидан 2-си (энг кўпи 1,0)."],
    ["Ой ёпилиши", "Ой тугагач, кечикиб киритилган буйруқлар учун кейинги ойнинг 5-санаси 09:00 гача очиқ туради, кейин автоматик ёпилади ва рақамлари қотади. Админ олдинроқ ёпиши ёки қайта очиши мумкин."],
    ["Манба", "Verifix API: ҳар кеча 23:40 да ва «Verifix'дан янгилаш» тугмасида ўқилади. Verifix фақат бугунги ҳолатни билади, шунинг учун ой охиридаги рўйхат ўша куни сақлаб қўйилади. Ҳисоб 2026 йил октябрдан бошланган."],
    ["Ўтган ойлар", "2026 йил октябргача бўлган ойлар (2025 йил январдан) «Ҳисоблаш» тугмаси билан ҳисобланади ва сақланади; «Янгилаш» қайта ҳисоблайди. Кетганлар — Verifix'даги бўшатиш санаси бўйича (кейин қайта ишга кирганлар бўшатиш буйруғидан); ишлаётганлар — ҳозирги бўлимлари бўйича, чунки Verifix ўтмишдаги бўлимни сақламайди. Шунинг учун бундай ой тахминий."],
  ],

  closeTitle: "{month} ёпилсинми?",
  closeMsg: "Ёпилгандан кейин бу ойнинг рақамлари ўзгармайди. Кейин киритилган буйруқлар алоҳида кўрсатилади.",
  reopenTitle: "{month} қайта очилсинми?",
  reopenMsg: "Кетганлар яна Verifix'дан жонли ўқилади. Ишлаётганлар рўйхати ой охирида олинган ҳолича қолади. Сиз ёпмагунча ой очиқ туради.",

  tReadStarted: "Verifix ўқилмоқда — бир неча дақиқа", tReadBusy: "Ўқиш аллақачон кетмоқда",
  tReadDone: "Verifix ўқилди", tReadFailed: "Verifix ўқилмади: {e}",
  tClosed: "{month} ёпилди", tReopened: "{month} қайта очилди", tFailed: "Бажарилмади: {e}",
  tExportDl: "Excel юклаб олинди", tExportTg: "Excel Telegram'га юборилди", tExportFail: "Excel тайёрланмади: {e}",
  loadFailed: "Маълумот юкланмади", loadFailedMsg: "Сервер жавоб бермади. Қайта уриниб кўринг.",

  mMonth: "Ой", mState: "Ҳолат", mList: "Рўйхат олинган", mRead: "Verifix ўқилган", mScope: "Танлов",
  mScopeAll: "Бутун завод",
  xl: {
    sheetSummary: "Умумий", sheetLeaders: "Лидерлар", sheetCells: "Ячейкалар", sheetLeft: "Кетганлар",
    sheetWorking: "Ишлаётганлар", left: "Кетганлар", working: "Ой охирида ишлаётганлар",
    rate: "Қўнимсизлик (йиллик)", leaders: "Баҳоланган лидерлар", formula: "Қандай ҳисобланади",
    bands: "Балл шкаласи", bandRate: "Қўнимсизлик", bandScore: "Балл", bandPoints: "KPI балли",
    nobody: "Ҳеч кимга ҳисобланмаганлар", colN: "№", colLeader: "Лидер", colBrigadir: "Бригадир",
    colCells: "Ячейкалар", colCell: "Ячейка", colShift: "Смена", colWorking: "Ишлаётганлар",
    colLeft: "Кетганлар", colRate: "Қўнимсизлик, %", colScore: "Балл", colPoints: "KPI балли",
    colName: "Ф.И.Ш.", colJob: "Лавозим", colHired: "Ишга кирган", colLeftOn: "Кетган сана",
    colDays: "Ишлаган куни", colReason: "Сабаб", colNote: "Изоҳ", colCounted: "Кимга ҳисобланди",
    countedLeader: "Лидерга", countedNoLeader: "Лидерсиз ячейка", countedNoCell: "Ячейка /cells'да йўқ",
    noLeader: "Лидер йўқ", nobodyNoLeader: "Лидерсиз ячейкалардан кетганлар",
    nobodyNoCell: "/cells'да йўқ код", nobodyOther: "Ячейка бўлмаган бўлимлардан кетганлар (KPI'га кирмайди)",
  },
};

const ru = {
  title: "Текучесть кадров",
  tabLeaders: "Лидеры", tabCells: "Ячейки", tabLeft: "Уволенные",
  search: "Лидер, ячейка или имя",
  fShift: "Смена", fBrigadir: "Бригадир", shiftN: "Смена {n}", all: "Все",
  excel: "Excel", refresh: "Обновить из Verifix", rulesBtn: "Как считается?",
  close: "Закрыть месяц", reopen: "Открыть заново", cancel: "Отмена", done: "Закрыть",
  retry: "Повторить",

  stOpen: "Месяц идёт", stClosing: "Ждёт закрытия", stClosed: "Закрыт",
  lineOpen: "На сегодня: {from} – {asOf}. До конца месяца цифры меняются; {closeAt} месяц закроется автоматически.",
  lineClosing: "Месяц закончился. Список работающих снят {rosterAt}. Открыт для поздних приказов — {closeAt} закроется автоматически.",
  lineClosingApprox: "Месяц закончился, но список на конец месяца не снят — работающие посчитаны по текущим отделам, приблизительно. {closeAt} закроется автоматически.",
  lineReopened: "Открыт заново: {by} ({at}). Остаётся открытым, пока админ не закроет.",
  lineClosed: "Закрыт {at} ({by}). Цифры этого месяца больше не меняются.",
  bySystem: "автоматически",
  before: "Самый ранний месяц для расчёта — январь 2025 года.",
  beforeTitle: "Этот месяц не считается",
  future: "Этот месяц ещё не начался.",
  stSaved: "Сохранённый расчёт",
  lineSaved: "Рассчитан {at} по данным Verifix на тот день ({by}). «Обновить» пересчитает по сегодняшним данным.",
  compute: "Рассчитать", update: "Обновить", computing: "Считаем…",
  pastTitle: "{month} ещё не рассчитан",
  pastMsg: "Месяцы до октября 2026 года не считаются сами. «Рассчитать» читает Verifix сейчас, считает месяц и сохраняет его — после этого кнопка станет «Обновить». Verifix не хранит прошлые отделы, поэтому работающие считаются по текущим отделам: результат приблизительный.",
  pastNoAdmin: "Месяц рассчитывает админ.",
  nPastApprox: "Этот прошлый месяц посчитан по сегодняшним данным Verifix: работающие — по текущим отделам, лидеры — по текущему /cells. Кто с тех пор сменил отдел, мог попасть в другую ячейку.",
  nRehired: "{n} чел. после увольнения снова приняты — взяты из приказа об увольнении, ячейка по текущему отделу (≈).",
  approxHint: "Позже снова принят: ячейка по текущему отделу",
  tComputeStarted: "Считаем {month} — несколько минут", tComputed: "{month} рассчитан и сохранён",

  readAt: "Verifix: {at}", readNever: "Verifix ещё не читался", readRunning: "Читаем Verifix…",
  readFailed: "Последнее чтение не удалось: {e}",
  readStale: "Verifix не читался больше 30 часов — цифры могут быть устаревшими.",
  notConfTitle: "Verifix не подключён",
  notConfMsg: "Админ-панель → Инструменты → карточка Verifix: введите логин и пароль.",
  noReadTitle: "Verifix ещё не читался",
  noReadMsg: "Читается каждую ночь в 23:40. Прочитать сейчас — несколько минут.",
  readNow: "Прочитать сейчас",

  kLeft: "Уволено", kLeftSub: "из них {n} засчитаны лидерам",
  kWorking: "Работают на конец месяца", kWorkingOpen: "Работают сейчас", kWorkingSub: "в {n} ячейках",
  kRate: "Текучесть (годовая)", kRateSub: "{left} ÷ {working} × 12",
  kLeaders: "Оценено лидеров", kLeadersSub: "у {n} в ячейках никого нет",
  kLeadersAll: "оценены все",

  formula: "Текучесть = уволено ÷ работают × 12",
  formulaHere: "В текущем выборе",
  smallTeam: "В маленькой команде даже один уволенный даёт большой процент: в ячейке из 12 человек 1 человек = 100%.",

  nTitle: "Не повлияли ни на чей балл",
  nNoLeader: "{n} чел. уволились из ячеек без лидера.",
  nUnreg: "{codes} — этих кодов нет в списке /cells: {w} работающих и {l} уволенных не посчитаны. Добавьте ячейку в /cells и назначьте лидера — войдёт в следующий расчёт.",
  nOther: "{n} чел. уволились из отделов, которые не являются ячейками (охрана, IT, водители и т. д.) — в этот KPI не входят.",
  nNoPeople: "У {n} лидеров в ячейках в Verifix никто не работает — возможно, код ячейки не совпадает с кодом отдела в Verifix.",
  nReasons: "Причины увольнения не пришли из Verifix: в API-роли не открыта форма «Увольнения». На расчёт не влияет.",
  nRosterLate: "Список снят через {n} дн. после конца месяца — переводы за эти дни уже учтены.",
  nDropped: "{n} чел. уволены датой этого месяца уже после снятия списка — исключены из работающих.",
  nLate: "После закрытия месяца в Verifix появилось {added} новых увольнений и {gone} отменённых — в расчёт не вошли. Чтобы учесть, откройте месяц заново.",

  colN: "№", colLeader: "Лидер", colBrigadir: "Бригадир", colCells: "Ячейки", colCell: "Ячейка",
  colShift: "Смена", colWorking: "Работают", colLeft: "Уволено", colRate: "Текучесть", colScore: "Балл",
  colPoints: "KPI", colName: "ФИО", colJob: "Должность", colHired: "Принят", colLeftOn: "Уволен",
  colTenure: "Стаж", colReason: "Причина", colCounted: "Кому засчитан",
  hWorking: "Работают на конец месяца (в текущем месяце — сейчас)",
  hLeft: "Уволены в течение месяца",
  hRate: "Уволено ÷ работают × 12, до одного знака",
  hScore: "1–5 по шкале баллов",
  hPoints: "Балл × 20% — доля в KPI лидеров (максимум 1,0)",
  countedLeader: "Лидеру", countedNoLeader: "Без лидера", countedNoCell: "Нет в /cells",
  noLeader: "Нет лидера", acting: "Вместо лидера", archived: "В архиве",
  noRateHint: "Никто не работает — посчитать нельзя",
  tLeaders: "KPI лидеров", tCells: "Ячейки", tLeft: "Уволенные",
  nLeaders: "{n} лидеров", nCells: "{n} ячеек", nPeople: "{n} чел.",
  nothing: "Ничего не найдено", noneLeft: "В этом месяце никто не уволился",
  days: "{n} дн.", months: "{n} мес.", years: "{y} г. {m} мес.",

  bandsTitle: "Шкала баллов", kpiLine: "Балл KPI = балл × {w}%",
  provisional: "Месяц не закончился — балл будет меняться до конца месяца",

  exCalc: "Расчёт", exCells: "Ячейки", exTotal: "Итого",
  exWorkingLeft: "{w} работают · {l} уволено",
  exNoWorking: "Никто не работает — текучесть посчитать нельзя, балл не ставится.",
  scoreN: "балл {n}",
  exScore: "{rate} → балл {score}", exPoints: "KPI: {score} × {w}% = {p}",
  exLeftList: "Уволенные", exWorkingList: "Работающие", exNone: "Никого",
  exLoadFail: "Список не загрузился", exWorkingAt: "на {date}",
  exWhyLeft: "Уволен в Verifix датой этого месяца; отдел на момент увольнения — эта ячейка.",
  exWhyWorking: "Работал в этот день, отдел — эта ячейка. Уволенные в этом месяце сюда не входят.",

  rulesTitle: "Как считается",
  rules: [
    ["Уволенный", "Каждый сотрудник, у которого в Verifix «Дата увольнения» приходится на этот месяц, — по любой причине: ушёл сам или уволен."],
    ["Работающий", "Сотрудник, работавший в последний день месяца (принят до этого дня и не уволен). Уволенные в этом месяце сюда не входят. В текущем месяце — состояние на день последнего чтения."],
    ["Ячейка", "Код отдела сотрудника в Verifix: для уволенного — отдел на момент увольнения, для работающего — на конец месяца. Учитываются только ячейки из списка /cells."],
    ["Лидер", "Лидер ячейки в /cells (на конец месяца). Если ячеек несколько, они считаются вместе: все уволенные ÷ все работающие × 12."],
    ["× 12", "Переводит один месяц в годовой показатель: если бы каждый месяц уходило столько же, какая доля команды сменилась бы за год."],
    ["Балл", "Процент округляется до одного знака и оценивается по шкале. Если никто не работает, балл не ставится."],
    ["KPI", "Балл × 20% — 2-й из 5 показателей KPI лидеров (максимум 1,0)."],
    ["Закрытие месяца", "После конца месяца он остаётся открытым для поздних приказов до 09:00 5-го числа следующего месяца, затем закрывается автоматически, и цифры фиксируются. Админ может закрыть раньше или открыть заново."],
    ["Источник", "Verifix API: читается каждую ночь в 23:40 и по кнопке «Обновить из Verifix». Verifix знает только сегодняшнее состояние, поэтому список на конец месяца сохраняется в тот же день. Расчёт ведётся с октября 2026 года."],
    ["Прошлые месяцы", "Месяцы до октября 2026 года (с января 2025) считаются кнопкой «Рассчитать» и сохраняются; «Обновить» пересчитывает. Уволенные — по дате увольнения в Verifix (кто потом снова принят — из приказа об увольнении); работающие — по текущим отделам, потому что Verifix не хранит прошлые отделы. Поэтому такой месяц приблизительный."],
  ],

  closeTitle: "Закрыть {month}?",
  closeMsg: "После закрытия цифры этого месяца не меняются. Приказы, внесённые позже, будут показаны отдельно.",
  reopenTitle: "Открыть {month} заново?",
  reopenMsg: "Уволенные снова читаются из Verifix вживую. Список работающих остаётся тем, что снят в конце месяца. Месяц открыт, пока вы его не закроете.",

  tReadStarted: "Читаем Verifix — несколько минут", tReadBusy: "Чтение уже идёт",
  tReadDone: "Verifix прочитан", tReadFailed: "Verifix не прочитан: {e}",
  tClosed: "{month} закрыт", tReopened: "{month} открыт заново", tFailed: "Не выполнено: {e}",
  tExportDl: "Excel скачан", tExportTg: "Excel отправлен в Telegram", tExportFail: "Excel не подготовлен: {e}",
  loadFailed: "Данные не загрузились", loadFailedMsg: "Сервер не ответил. Попробуйте ещё раз.",

  mMonth: "Месяц", mState: "Статус", mList: "Список снят", mRead: "Verifix прочитан", mScope: "Выбор",
  mScopeAll: "Весь завод",
  xl: {
    sheetSummary: "Обзор", sheetLeaders: "Лидеры", sheetCells: "Ячейки", sheetLeft: "Уволенные",
    sheetWorking: "Работающие", left: "Уволено", working: "Работают на конец месяца",
    rate: "Текучесть (годовая)", leaders: "Оценено лидеров", formula: "Как считается",
    bands: "Шкала баллов", bandRate: "Текучесть", bandScore: "Балл", bandPoints: "Балл KPI",
    nobody: "Не засчитаны никому", colN: "№", colLeader: "Лидер", colBrigadir: "Бригадир",
    colCells: "Ячейки", colCell: "Ячейка", colShift: "Смена", colWorking: "Работают",
    colLeft: "Уволено", colRate: "Текучесть, %", colScore: "Балл", colPoints: "Балл KPI",
    colName: "ФИО", colJob: "Должность", colHired: "Дата приёма", colLeftOn: "Дата увольнения",
    colDays: "Стаж, дней", colReason: "Причина", colNote: "Примечание", colCounted: "Кому засчитан",
    countedLeader: "Лидеру", countedNoLeader: "Ячейка без лидера", countedNoCell: "Ячейки нет в /cells",
    noLeader: "Нет лидера", nobodyNoLeader: "Уволены из ячеек без лидера",
    nobodyNoCell: "Кода нет в /cells", nobodyOther: "Уволены из отделов, которые не ячейки (в KPI не входят)",
  },
};

const en = {
  title: "Staff turnover",
  tabLeaders: "Leaders", tabCells: "Cells", tabLeft: "Leavers",
  search: "Leader, cell or name",
  fShift: "Shift", fBrigadir: "Supervisor", shiftN: "Shift {n}", all: "All",
  excel: "Excel", refresh: "Refresh from Verifix", rulesBtn: "How is it calculated?",
  close: "Close month", reopen: "Reopen", cancel: "Cancel", done: "Close",
  retry: "Retry",

  stOpen: "Month in progress", stClosing: "Waiting to close", stClosed: "Closed",
  lineOpen: "So far: {from} – {asOf}. Figures change until the month ends; it closes automatically at {closeAt}.",
  lineClosing: "The month has ended. The list of working people was taken at {rosterAt}. Open for late orders — closes automatically at {closeAt}.",
  lineClosingApprox: "The month has ended, but no list was taken at its end — working people are counted by their current units, approximately. Closes automatically at {closeAt}.",
  lineReopened: "Reopened by {by} ({at}). Stays open until an admin closes it.",
  lineClosed: "Closed at {at} ({by}). This month's figures no longer change.",
  bySystem: "automatically",
  before: "The earliest month that can be calculated is January 2025.",
  beforeTitle: "This month is not calculated",
  future: "This month has not started yet.",
  stSaved: "Saved calculation",
  lineSaved: "Calculated at {at} from Verifix's data of that day ({by}). «Update» recalculates it with today's data.",
  compute: "Calculate", update: "Update", computing: "Calculating…",
  pastTitle: "{month} is not calculated yet",
  pastMsg: "Months before October 2026 are not calculated by themselves. «Calculate» reads Verifix now, calculates the month and saves it — the button then becomes «Update». Verifix keeps no past units, so working people are counted in their current units: the result is approximate.",
  pastNoAdmin: "An admin calculates the month.",
  nPastApprox: "This past month was calculated from today's Verifix data: working people by their current units, leaders by today's /cells. Anyone who changed unit since may be counted in another cell.",
  nRehired: "{n} people were re-hired after leaving — taken from the dismissal order, their cell by today's unit (≈).",
  approxHint: "Re-hired later: the cell is their current unit",
  tComputeStarted: "Calculating {month} — a few minutes", tComputed: "{month} calculated and saved",

  readAt: "Verifix: {at}", readNever: "Verifix not read yet", readRunning: "Reading Verifix…",
  readFailed: "The last read failed: {e}",
  readStale: "Verifix has not been read for over 30 hours — figures may be out of date.",
  notConfTitle: "Verifix is not connected",
  notConfMsg: "Admin panel → Tools → the Verifix card: enter the login and password.",
  noReadTitle: "Verifix not read yet",
  noReadMsg: "It is read every night at 23:40. Reading now takes a few minutes.",
  readNow: "Read now",

  kLeft: "Left", kLeftSub: "{n} counted toward leaders",
  kWorking: "Working at month end", kWorkingOpen: "Working now", kWorkingSub: "in {n} cells",
  kRate: "Turnover (yearly)", kRateSub: "{left} ÷ {working} × 12",
  kLeaders: "Leaders scored", kLeadersSub: "{n} have nobody in their cells",
  kLeadersAll: "all scored",

  formula: "Turnover = left ÷ working × 12",
  formulaHere: "In the current selection",
  smallTeam: "In a small team even one leaver is a big percentage: in a cell of 12, one person = 100%.",

  nTitle: "Counted toward nobody's score",
  nNoLeader: "{n} people left cells that have no leader.",
  nUnreg: "{codes} — these codes are not on /cells: {w} working and {l} leavers were not counted. Add the cell on /cells and assign a leader to count it next time.",
  nOther: "{n} people left units that are not cells (security, IT, drivers, etc.) — not part of this KPI.",
  nNoPeople: "{n} leaders have nobody working in their cells on Verifix — the cell code may not match the Verifix unit code.",
  nReasons: "Leaving reasons did not come from Verifix: the «Увольнения» form is not open in the API role. The figures are not affected.",
  nRosterLate: "The list was taken {n} days after the month ended — unit changes in those days are included.",
  nDropped: "{n} people were dismissed with a date in this month after the list was taken — removed from the working count.",
  nLate: "After the month closed, Verifix shows {added} new departures and {gone} cancelled ones — not counted. Reopen the month to include them.",

  colN: "#", colLeader: "Leader", colBrigadir: "Supervisor", colCells: "Cells", colCell: "Cell",
  colShift: "Shift", colWorking: "Working", colLeft: "Left", colRate: "Turnover", colScore: "Score",
  colPoints: "KPI", colName: "Name", colJob: "Job", colHired: "Hired", colLeftOn: "Left on",
  colTenure: "Tenure", colReason: "Reason", colCounted: "Counted toward",
  hWorking: "Working at month end (in the current month — now)",
  hLeft: "Dismissed during the month",
  hRate: "Left ÷ working × 12, to one decimal",
  hScore: "1–5 by the score scale",
  hPoints: "Score × 20% — its share of the leaders' KPI (at most 1.0)",
  countedLeader: "Leader", countedNoLeader: "No leader", countedNoCell: "Not on /cells",
  noLeader: "No leader", acting: "In place of a leader", archived: "Archived",
  noRateHint: "Nobody working — cannot be calculated",
  tLeaders: "Leaders' KPI", tCells: "Cells", tLeft: "Leavers",
  nLeaders: "{n} leaders", nCells: "{n} cells", nPeople: "{n} people",
  nothing: "Nothing found", noneLeft: "Nobody left this month",
  days: "{n} d", months: "{n} mo", years: "{y} y {m} mo",

  bandsTitle: "Score scale", kpiLine: "KPI points = score × {w}%",
  provisional: "The month is not over — the score changes until it ends",

  exCalc: "Calculation", exCells: "Cells", exTotal: "Total",
  exWorkingLeft: "{w} working · {l} left",
  exNoWorking: "Nobody working — turnover cannot be calculated, no score.",
  scoreN: "score {n}",
  exScore: "{rate} → score {score}", exPoints: "KPI: {score} × {w}% = {p}",
  exLeftList: "Leavers", exWorkingList: "Working", exNone: "Nobody",
  exLoadFail: "The list did not load", exWorkingAt: "as of {date}",
  exWhyLeft: "Dismissed in Verifix with a date in this month; their unit when they left is this cell.",
  exWhyWorking: "Working on that day, in this cell's unit. People who left this month are not in this list.",

  rulesTitle: "How it is calculated",
  rules: [
    ["Leaver", "Every employee whose Verifix «Дата увольнения» (dismissal date) falls in the month — for any reason: they quit or were dismissed."],
    ["Working", "An employee working on the month's last day (hired by then and not dismissed). People who left during the month are not in this count. In the current month — the state on the day of the last read."],
    ["Cell", "The code of the employee's Verifix unit («отдел»): for a leaver, their unit when they left; for a working person, their unit at the month's end. Only cells on /cells count."],
    ["Leader", "The cell's leader on /cells (at the month's end). Several cells are counted together: all leavers ÷ all working × 12."],
    ["× 12", "Turns one month into a yearly rate: if this many left every month, what share of the team would change in a year."],
    ["Score", "The percentage is rounded to one decimal and judged by the scale. With nobody working there is no score."],
    ["KPI", "Score × 20% — the 2nd of the 5 indicators of the leaders' KPI (at most 1.0)."],
    ["Month close", "After a month ends it stays open for late orders until 09:00 on the 5th of the next month, then closes automatically and its figures freeze. An admin can close it earlier or reopen it."],
    ["Source", "The Verifix API: read every night at 23:40 and by «Refresh from Verifix». Verifix only knows today's state, so the month-end list is saved on that day. Calculated from October 2026."],
    ["Past months", "Months before October 2026 (from January 2025) are calculated with «Calculate» and saved; «Update» recalculates. Leavers — by the Verifix dismissal date (people re-hired later, from the dismissal order); working people — by their current units, because Verifix keeps no past unit. Such a month is therefore approximate."],
  ],

  closeTitle: "Close {month}?",
  closeMsg: "After closing, this month's figures no longer change. Orders entered later are shown separately.",
  reopenTitle: "Reopen {month}?",
  reopenMsg: "Leavers are read live from Verifix again. The list of working people stays the one taken at the month's end. The month stays open until you close it.",

  tReadStarted: "Reading Verifix — a few minutes", tReadBusy: "A read is already running",
  tReadDone: "Verifix read", tReadFailed: "Verifix not read: {e}",
  tClosed: "{month} closed", tReopened: "{month} reopened", tFailed: "Failed: {e}",
  tExportDl: "Excel downloaded", tExportTg: "Excel sent to Telegram", tExportFail: "Excel not prepared: {e}",
  loadFailed: "The data did not load", loadFailedMsg: "The server did not answer. Try again.",

  mMonth: "Month", mState: "State", mList: "List taken", mRead: "Verifix read", mScope: "Selection",
  mScopeAll: "Whole plant",
  xl: {
    sheetSummary: "Summary", sheetLeaders: "Leaders", sheetCells: "Cells", sheetLeft: "Leavers",
    sheetWorking: "Working", left: "Left", working: "Working at month end",
    rate: "Turnover (yearly)", leaders: "Leaders scored", formula: "How it is calculated",
    bands: "Score scale", bandRate: "Turnover", bandScore: "Score", bandPoints: "KPI points",
    nobody: "Counted toward nobody", colN: "#", colLeader: "Leader", colBrigadir: "Supervisor",
    colCells: "Cells", colCell: "Cell", colShift: "Shift", colWorking: "Working",
    colLeft: "Left", colRate: "Turnover, %", colScore: "Score", colPoints: "KPI points",
    colName: "Name", colJob: "Job", colHired: "Hired", colLeftOn: "Left on",
    colDays: "Tenure, days", colReason: "Reason", colNote: "Note", colCounted: "Counted toward",
    countedLeader: "Leader", countedNoLeader: "Cell without a leader", countedNoCell: "Cell not on /cells",
    noLeader: "No leader", nobodyNoLeader: "Left cells without a leader",
    nobodyNoCell: "Code not on /cells", nobodyOther: "Left units that are not cells (not in the KPI)",
  },
};

export const TXT = { uz, uz_cyrl, ru, en };
