// «Ishchi havotirlari» — the page's words in the four platform languages.
// Kept beside the page (as before the redesign) rather than in translations.js;
// `fill(s, {n: 3})` puts the numbers in. Status words live in ST_LBL so the
// page, its chips and the Excel file name a status one way.

export const LI = { uz: 0, uz_cyrl: 1, ru: 2, en: 3 };

// «todo» is the word /cell-concerns prints for the same rows («Yangi»): the
// platform knows a concern was not taken into work, never that it was not read.
export const ST_LBL = {
  done:     ["Hal bo'lgan", "Ҳал бўлган", "Решено", "Resolved"],
  doing:    ["Jarayonda", "Жараёнда", "В работе", "In progress"],
  todo:     ["Yangi", "Янги", "Новый", "New"],
  uplifted: ["Ko'tarilgan", "Кўтарилган", "Передано выше", "Escalated"],
};

export const fill = (s, vars) =>
  String(s ?? "").replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? `{${k}}`));

export const TXT = {
  uz: {
    title: "Ishchi havotirlari",
    vRating: "Reyting", vList: "Ro'yxat",
    loadFailed: "Ma'lumotlarni yuklab bo'lmadi",
    loadFailedMsg: "Server javob bermadi yoki aloqa uzildi. Qayta urinib ko'ring.",
    retry: "Qayta urinish",
    errRange: "Davr noto'g'ri: boshlanish sanasi tugash sanasidan keyin",
    errStats: "Umumiy ko'rsatkich, brigadirlar, yacheykalar va dinamika yuklanmadi",
    errLeaders: "Liderlar reytingi yuklanmadi", errList: "Havotirlar ro'yxati yuklanmadi",
    errOpen: "Ochiq havotirlar yuklanmadi", errMeta: "Sahifa ma'lumotlari yuklanmadi",
    fLeadersFailed: "Liderlar bo'yicha raqamlar yuklanmadi",
    emptyTitle: "Hali havotir yo'q",
    emptyNote: "Ishchilar «Yacheyka havotirlari» sahifasida yozgan havotirlar shu yerda hisoblanadi.",
    emptyGo: "Yacheyka havotirlari",
    emptyPeriodTitle: "Bu davrda havotir yo'q",
    emptyPeriodMsg: "Tanlangan davrda ishchilar havotir yozmagan.",
    emptyPeriodFiltered: "Tanlangan davr va filtrlarga mos havotir topilmadi.",
    showAllTime: "Barcha vaqtni ko'rsatish",
    clearFilters: "Filtrlarni tozalash",
    hLabel: "Hal bo'lgan havotirlar",
    hInfo: "Ishchilar «Yacheyka havotirlari» sahifasida liderlarga yozgan havotirlar. Har biri u yozilgan liderga hisoblanadi: % = hal bo'lgan ÷ (jami − ko'tarilgan). Brigadirga yoki undan yuqoriga ko'tarilgan havotir liderning foiziga kirmaydi — keyin hal bo'lgan bo'lsa ham. Reytingda faqat Verifixda lider lavozimidagilar. Ishchilar yozilgan ism bo'yicha sanaladi.",
    hOf: "{total} ta havotirdan {done} tasi hal bo'lgan",
    hOfRated: "Liderda qolgan {rated} ta havotirdan {done} tasi hal bo'lgan",
    hUpOut: "{u} tasi yuqoriga ko'tarilgan — foizga kirmaydi",
    upDone: "yuqorida hal qilingan",
    hPrevLead: "oldingi {n} kun", hPrevNoneTail: "havotir bo'lmagan",
    hUp: "+{d} punkt", hDown: "−{d} punkt", hSame: "deyarli o'zgarmagan",
    hPrevTip: "{from} – {to}: {done} / {total}, o'sha davr tugagandan keyin xuddi shuncha vaqt o'tgandagi holat",
    hLow: "kam ma'lumot — 5 tadan kam havotir",
    fWorkers: "{n} ishchi yozgan",
    fWith: "{n} liderga yozilgan",
    fNone: "{n} lider havotir olmagan",
    fUnassigned: "{n} ta havotirda lider ko'rsatilmagan — reytingga kirmaydi",
    rTitle: "Liderlar reytingi",
    rSub: "% hal bo'lgan bo'yicha, eng yaxshisi tepada",
    rCount: "{n} lider",
    rRanked: "{k} tasi reytingda", showMore: "Yana {n} liderni ko'rsatish",
    rSearch: "Lider qidirish…",
    colRank: "#", colLeader: "Lider", colStatuses: "Holatlar", colTotal: "Jami",
    colOpen: "Ochiq", colPct: "% hal bo'lgan", colOpenHint: "Liderda: yangi + jarayonda", colPctHint: "% = hal bo'lgan ÷ (jami − ko'tarilgan)",
    gLow: "Kam ma'lumot — 5 tadan kam havotir, reytingga kirmaydi",
    gNone: "Havotir olmagan liderlar",
    gNotLeader: "Reytingga kirmaydi — Verifixda lider lavozimida emas",
    kindActing: "Lider o'rnida", kindNone: "Lavozimi aniqlanmagan",
    showNone: "{n} lider havotir olmagan — ko'rsatish",
    hideNone: "Havotir olmaganlarni yashirish",
    bandLowL: "n < {m}",
    bandsEdit: "Chegaralar", bandsTitle: "KPI chegaralari",
    bandGreenL: "Yashil chegara (≥ %)", bandYellowL: "Sariq chegara (≥ %)",
    bandsHint: "Sariqdan pasti qizil hisoblanadi. Chegaralar butun platforma uchun bitta.",
    bandsSaved: "Chegaralar saqlandi", bandsErr: "Saqlab bo'lmadi",
    noMatchLeaders: "Qidiruvga mos lider yo'q",
    uTitle: "Brigadirlar",
    uSub: "% hal bo'lgan bo'yicha · bosing — sahifa shu brigadirga toraytiriladi",
    uLeaders: "{n} liderga yozilgan",
    cTitle: "Yacheykalar — hal bo'lmagan havotirlar",
    cSub: "eng ko'p ochiq havotiri bor yacheykalar",
    cMine: "Yacheykalarim", cMineSub: "har bir yacheykadagi havotirlar holati",
    cNoOpen: "Liderlarda ochiq havotir yo'q",
    cOpen: "ochiq",
    dTitle: "Kunlik dinamika",
    dSub: "har kuni kelib tushgan havotirlar va ularning hozirgi holati",
    dTitleWeek: "Haftalik dinamika",
    dSubWeek: "har hafta kelib tushgan havotirlar va ularning hozirgi holati",
    dAxis: "havotir, ta",
    myOpenTitle: "Hal bo'lmagan havotirlaringiz", myOpenSub: "eng eskisi birinchi",
    myNoOpen: "Hal bo'lmagan havotir yo'q",
    myUpTitle: "Brigadirda", myActTitle: "Sizda", moreOf: "Yana {n} tasini ko'rish",
    goAct: "«Yacheyka havotirlari»da ochish", seeAll: "Barchasini ko'rish",
    lmRank: "reytingdagi {n} lider ichida {r}-o'rin",
    lmUnranked: "Reytingda emas — 5 tadan kam havotir",
    lmNotLeader: "Reytingda emas — Verifixda lider lavozimida emas",
    lmNone: "Bu davrda bu liderga havotir yozilmagan",
    lmOpenTitle: "Liderda ochiq havotirlar", lmShowing: "{n} tadan {k} tasi ko'rsatilgan",
    lmAll: "Barcha havotirlarini ko'rish", lmCells: "Yacheykalar",
    ageToday: "bugun", ageDays: "{n} kun",
    regTitle: "Havotirlar", regSearch: "Matn, ishchi, lider yoki №", regCount: "{n} ta",
    colNo: "№", colDate: "Sana", colCell: "Yacheyka", colText: "Havotir", colWorker: "Ishchi",
    colTextWho: "Havotir · ishchi → lider", colTextWorker: "Havotir · ishchi",
    colStatus: "Holat",
    noMatch: "Mos yozuv topilmadi",
    mTitle: "Havotir", mBrig: "Brigadir", mCategory: "Bo'lim", mStep: "Bosqich",
    mDoneOn: "Hal qilingan sana", mOpen: "«{page}»da ochish",
    close: "Yopish", cancel: "Bekor qilish", save: "Saqlash",
    fBrig: "Brigadir", fLeader: "Lider", fCell: "Yacheyka", fStatus: "Holat",
    gWho: "Kim va qayerda", gWhat: "Holat",
    nByBrig: "Tanlangan brigadir bo'yicha toraytirilgan · {n}",
    nByLeader: "Tanlangan lider bo'yicha toraytirilgan · {n}",
    widenBrig: "Barcha brigadirlarni ko'rsatish", widenLeader: "Barcha liderlarni ko'rsatish",
    emptyList: "Bu tanlovda variant yo'q",
    stUpHint: "Brigadirga (yoki undan yuqoriga) ko'tarilgan — keyin hal bo'lgan bo'lsa ham liderning foiziga kirmaydi",
    uNarrowed: "Sahifa {name} bo'yicha toraytirildi — filtr chipidagi × bilan qaytariladi",
    rowTotOpen: "jami {t} · ochiq {o}", rowTotUpOpen: "jami {t} · ko'tarilgan {u} · ochiq {o}", cTotal: "jami {n}",
    hShort: "Qisqa davr ({n} kun): yangi havotirlar hal bo'lishga ulgurmagan — rang bilan baholanmaydi",
    startTitle: "Ma'lumotlar {date} dan boshlanadi",
    startMsg: "Ishchilar «Yacheyka havotirlari»ga {date} dan yoza boshlagan.",
    startBtn: "{date} dan ko'rsatish",
    xSub: "Ishchilar «Yacheyka havotirlari» sahifasida liderlarga yozgan havotirlar — liderlar KPI",
    xBtn: "Excel", xTitle: "Excel eksport",
    xModalQ: "Filtrlar qo'llangan. Faylga nimani kiritamiz?",
    xOptFiltered: "Faqat filtrlangan yozuvlar", xOptFilteredD: "Ekranda ko'rinayotgan kesim bo'yicha",
    xOptAll: "Davrning barcha ma'lumotlari", xOptAllD: "Tanlangan davr uchun to'liq manzara — filtrlarsiz",
    xExport: "Eksport qilish", xDownloaded: "Fayl yuklab olindi", xSentTg: "Fayl Telegramga yuborildi",
    xFailed: "Eksport qilib bo'lmadi",
    xPeriod: "Davr", xPlant: "Zavod", xAllPlants: "Barcha zavodlar",
    xFilters: "Filtrlar", xScopeAll: "Barcha ma'lumotlar (filtrsiz)",
    xGenerated: "Shakllantirildi", xSearch: "Qidiruv",
    xSheets: { overview: "Umumiy", leaders: "Liderlar reytingi", register: "Havotirlar" },
    xLabels: {
      secKpi: "Asosiy ko'rsatkichlar",
      kTotal: "Jami havotirlar", kResolved: "Hal bo'lgan", kDoing: "Jarayonda",
      kOpen: "Liderda ochiq", kOpenHint: "yangi + jarayonda",
      kWorkers: "Faol ishchilar", kWorkersHint: "yozilgan ism bo'yicha",
      secDaily: "Kunlik dinamika", secDailySub: "holatlar bo'yicha, kelib tushgan sana",
      secBrig: "Brigadirlar kesimi", secBrigSub: "tanlangan davr, holatlar bo'yicha",
      secCells: "Yacheykalar — hal bo'lmaganlar TOP", secCellsSub: "eng ko'p ochiq havotirli yacheykalar",
      secLeaders: "Liderlar reytingi", secLeadersSub: "har bir lider — havotir yuborilgan lider bo'yicha",
      secRegister: "Havotirlar reyestri",
      colLeader: "Lider", colBrig: "Brigadir", colCells: "Yacheykalar", colTotal: "Jami",
      colDone: "Hal bo'lgan", colDoing: "Jarayonda", colOpen: "Ochiq (liderda)", colPct: "% hal bo'lgan",
      colDate: "Sana", colCell: "Yacheyka", colOwner: "Ishchi", colText: "Havotir", colStatus: "Holat",
      unassignedRow: "Lidersiz havotirlar",
      lowNHint: "5 tadan kam havotir — reyting uchun yetarli emas", noMatch: "Mos yozuv topilmadi",
      rows: "ta", concernsWord: "havotir", leadersWord: "lider", kamBand: "kam ma'lumot",
      rateNote: "% = hal bo'lgan ÷ (jami − ko'tarilgan): yuqoriga ko'tarilgan havotir liderning foiziga kirmaydi. Reytingda faqat Verifixda lider lavozimidagilar.",
      kindLabels: { acting: "Lider o'rnida", none: "Lavozimi aniqlanmagan" },
    },
  },
  uz_cyrl: {
    title: "Ишчи ҳавотирлари",
    vRating: "Рейтинг", vList: "Рўйхат",
    loadFailed: "Маълумотларни юклаб бўлмади",
    loadFailedMsg: "Сервер жавоб бермади ёки алоқа узилди. Қайта уриниб кўринг.",
    retry: "Қайта уриниш",
    errRange: "Давр нотўғри: бошланиш санаси тугаш санасидан кейин",
    errStats: "Умумий кўрсаткич, бригадирлар, ячейкалар ва динамика юкланмади",
    errLeaders: "Лидерлар рейтинги юкланмади", errList: "Ҳавотирлар рўйхати юкланмади",
    errOpen: "Очиқ ҳавотирлар юкланмади", errMeta: "Саҳифа маълумотлари юкланмади",
    fLeadersFailed: "Лидерлар бўйича рақамлар юкланмади",
    emptyTitle: "Ҳали ҳавотир йўқ",
    emptyNote: "Ишчилар «Ячейка ҳавотирлари» саҳифасида ёзган ҳавотирлар шу ерда ҳисобланади.",
    emptyGo: "Ячейка ҳавотирлари",
    emptyPeriodTitle: "Бу даврда ҳавотир йўқ",
    emptyPeriodMsg: "Танланган даврда ишчилар ҳавотир ёзмаган.",
    emptyPeriodFiltered: "Танланган давр ва филтрларга мос ҳавотир топилмади.",
    showAllTime: "Барча вақтни кўрсатиш",
    clearFilters: "Филтрларни тозалаш",
    hLabel: "Ҳал бўлган ҳавотирлар",
    hInfo: "Ишчилар «Ячейка ҳавотирлари» саҳифасида лидерларга ёзган ҳавотирлар. Ҳар бири у ёзилган лидерга ҳисобланади: % = ҳал бўлган ÷ (жами − кўтарилган). Бригадирга ёки ундан юқорига кўтарилган ҳавотир лидернинг фоизига кирмайди — кейин ҳал бўлган бўлса ҳам. Рейтингда фақат Verifixда лидер лавозимидагилар. Ишчилар ёзилган исм бўйича саналади.",
    hOf: "{total} та ҳавотирдан {done} таси ҳал бўлган",
    hOfRated: "Лидерда қолган {rated} та ҳавотирдан {done} таси ҳал бўлган",
    hUpOut: "{u} таси юқорига кўтарилган — фоизга кирмайди",
    upDone: "юқорида ҳал қилинган",
    hPrevLead: "олдинги {n} кун", hPrevNoneTail: "ҳавотир бўлмаган",
    hUp: "+{d} пункт", hDown: "−{d} пункт", hSame: "деярли ўзгармаган",
    hPrevTip: "{from} – {to}: {done} / {total}, ўша давр тугагандан кейин худди шунча вақт ўтгандаги ҳолат",
    hLow: "кам маълумот — 5 тадан кам ҳавотир",
    fWorkers: "{n} ишчи ёзган",
    fWith: "{n} лидерга ёзилган",
    fNone: "{n} лидер ҳавотир олмаган",
    fUnassigned: "{n} та ҳавотирда лидер кўрсатилмаган — рейтингга кирмайди",
    rTitle: "Лидерлар рейтинги",
    rSub: "% ҳал бўлган бўйича, энг яхшиси тепада",
    rCount: "{n} лидер",
    rRanked: "{k} таси рейтингда", showMore: "Яна {n} лидерни кўрсатиш",
    rSearch: "Лидер қидириш…",
    colRank: "#", colLeader: "Лидер", colStatuses: "Ҳолатлар", colTotal: "Жами",
    colOpen: "Очиқ", colPct: "% ҳал бўлган", colOpenHint: "Лидерда: янги + жараёнда", colPctHint: "% = ҳал бўлган ÷ (жами − кўтарилган)",
    gLow: "Кам маълумот — 5 тадан кам ҳавотир, рейтингга кирмайди",
    gNone: "Ҳавотир олмаган лидерлар",
    gNotLeader: "Рейтингга кирмайди — Verifixда лидер лавозимида эмас",
    kindActing: "Лидер ўрнида", kindNone: "Лавозими аниқланмаган",
    showNone: "{n} лидер ҳавотир олмаган — кўрсатиш",
    hideNone: "Ҳавотир олмаганларни яшириш",
    bandLowL: "n < {m}",
    bandsEdit: "Чегаралар", bandsTitle: "KPI чегаралари",
    bandGreenL: "Яшил чегара (≥ %)", bandYellowL: "Сариқ чегара (≥ %)",
    bandsHint: "Сариқдан пасти қизил ҳисобланади. Чегаралар бутун платформа учун битта.",
    bandsSaved: "Чегаралар сақланди", bandsErr: "Сақлаб бўлмади",
    noMatchLeaders: "Қидирувга мос лидер йўқ",
    uTitle: "Бригадирлар",
    uSub: "% ҳал бўлган бўйича · босинг — саҳифа шу бригадирга торайтирилади",
    uLeaders: "{n} лидерга ёзилган",
    cTitle: "Ячейкалар — ҳал бўлмаган ҳавотирлар",
    cSub: "энг кўп очиқ ҳавотири бор ячейкалар",
    cMine: "Ячейкаларим", cMineSub: "ҳар бир ячейкадаги ҳавотирлар ҳолати",
    cNoOpen: "Лидерларда очиқ ҳавотир йўқ",
    cOpen: "очиқ",
    dTitle: "Кунлик динамика",
    dSub: "ҳар куни келиб тушган ҳавотирлар ва уларнинг ҳозирги ҳолати",
    dTitleWeek: "Ҳафталик динамика",
    dSubWeek: "ҳар ҳафта келиб тушган ҳавотирлар ва уларнинг ҳозирги ҳолати",
    dAxis: "ҳавотир, та",
    myOpenTitle: "Ҳал бўлмаган ҳавотирларингиз", myOpenSub: "энг эскиси биринчи",
    myNoOpen: "Ҳал бўлмаган ҳавотир йўқ",
    myUpTitle: "Бригадирда", myActTitle: "Сизда", moreOf: "Яна {n} тасини кўриш",
    goAct: "«Ячейка ҳавотирлари»да очиш", seeAll: "Барчасини кўриш",
    lmRank: "рейтингдаги {n} лидер ичида {r}-ўрин",
    lmUnranked: "Рейтингда эмас — 5 тадан кам ҳавотир",
    lmNotLeader: "Рейтингда эмас — Verifixда лидер лавозимида эмас",
    lmNone: "Бу даврда бу лидерга ҳавотир ёзилмаган",
    lmOpenTitle: "Лидерда очиқ ҳавотирлар", lmShowing: "{n} тадан {k} таси кўрсатилган",
    lmAll: "Барча ҳавотирларини кўриш", lmCells: "Ячейкалар",
    ageToday: "бугун", ageDays: "{n} кун",
    regTitle: "Ҳавотирлар", regSearch: "Матн, ишчи, лидер ёки №", regCount: "{n} та",
    colNo: "№", colDate: "Сана", colCell: "Ячейка", colText: "Ҳавотир", colWorker: "Ишчи",
    colTextWho: "Ҳавотир · ишчи → лидер", colTextWorker: "Ҳавотир · ишчи",
    colStatus: "Ҳолат",
    noMatch: "Мос ёзув топилмади",
    mTitle: "Ҳавотир", mBrig: "Бригадир", mCategory: "Бўлим", mStep: "Босқич",
    mDoneOn: "Ҳал қилинган сана", mOpen: "«{page}»да очиш",
    close: "Ёпиш", cancel: "Бекор қилиш", save: "Сақлаш",
    fBrig: "Бригадир", fLeader: "Лидер", fCell: "Ячейка", fStatus: "Ҳолат",
    gWho: "Ким ва қаерда", gWhat: "Ҳолат",
    nByBrig: "Танланган бригадир бўйича торайтирилган · {n}",
    nByLeader: "Танланган лидер бўйича торайтирилган · {n}",
    widenBrig: "Барча бригадирларни кўрсатиш", widenLeader: "Барча лидерларни кўрсатиш",
    emptyList: "Бу танловда вариант йўқ",
    stUpHint: "Бригадирга (ёки ундан юқорига) кўтарилган — кейин ҳал бўлган бўлса ҳам лидернинг фоизига кирмайди",
    uNarrowed: "Саҳифа {name} бўйича торайтирилди — филтр чипидаги × билан қайтарилади",
    rowTotOpen: "жами {t} · очиқ {o}", rowTotUpOpen: "жами {t} · кўтарилган {u} · очиқ {o}", cTotal: "жами {n}",
    hShort: "Қисқа давр ({n} кун): янги ҳавотирлар ҳал бўлишга улгурмаган — ранг билан баҳоланмайди",
    startTitle: "Маълумотлар {date} дан бошланади",
    startMsg: "Ишчилар «Ячейка ҳавотирлари»га {date} дан ёза бошлаган.",
    startBtn: "{date} дан кўрсатиш",
    xSub: "Ишчилар «Ячейка ҳавотирлари» саҳифасида лидерларга ёзган ҳавотирлар — лидерлар KPI",
    xBtn: "Excel", xTitle: "Excel экспорт",
    xModalQ: "Филтрлар қўлланган. Файлга нимани киритамиз?",
    xOptFiltered: "Фақат филтрланган ёзувлар", xOptFilteredD: "Экранда кўринаётган кесим бўйича",
    xOptAll: "Даврнинг барча маълумотлари", xOptAllD: "Танланган давр учун тўлиқ манзара — филтрларсиз",
    xExport: "Экспорт қилиш", xDownloaded: "Файл юклаб олинди", xSentTg: "Файл Telegram'га юборилди",
    xFailed: "Экспорт қилиб бўлмади",
    xPeriod: "Давр", xPlant: "Завод", xAllPlants: "Барча заводлар",
    xFilters: "Филтрлар", xScopeAll: "Барча маълумотлар (филтрсиз)",
    xGenerated: "Шакллантирилди", xSearch: "Қидирув",
    xSheets: { overview: "Умумий", leaders: "Лидерлар рейтинги", register: "Ҳавотирлар" },
    xLabels: {
      secKpi: "Асосий кўрсаткичлар",
      kTotal: "Жами ҳавотирлар", kResolved: "Ҳал бўлган", kDoing: "Жараёнда",
      kOpen: "Лидерда очиқ", kOpenHint: "янги + жараёнда",
      kWorkers: "Фаол ишчилар", kWorkersHint: "ёзилган исм бўйича",
      secDaily: "Кунлик динамика", secDailySub: "ҳолатлар бўйича, келиб тушган сана",
      secBrig: "Бригадирлар кесими", secBrigSub: "танланган давр, ҳолатлар бўйича",
      secCells: "Ячейкалар — ҳал бўлмаганлар TOP", secCellsSub: "энг кўп очиқ ҳавотирли ячейкалар",
      secLeaders: "Лидерлар рейтинги", secLeadersSub: "ҳар бир лидер — ҳавотир юборилган лидер бўйича",
      secRegister: "Ҳавотирлар реестри",
      colLeader: "Лидер", colBrig: "Бригадир", colCells: "Ячейкалар", colTotal: "Жами",
      colDone: "Ҳал бўлган", colDoing: "Жараёнда", colOpen: "Очиқ (лидерда)", colPct: "% ҳал бўлган",
      colDate: "Сана", colCell: "Ячейка", colOwner: "Ишчи", colText: "Ҳавотир", colStatus: "Ҳолат",
      unassignedRow: "Лидерсиз ҳавотирлар",
      lowNHint: "5 тадан кам ҳавотир — рейтинг учун етарли эмас", noMatch: "Мос ёзув топилмади",
      rows: "та", concernsWord: "ҳавотир", leadersWord: "лидер", kamBand: "кам маълумот",
      rateNote: "% = ҳал бўлган ÷ (жами − кўтарилган): юқорига кўтарилган ҳавотир лидернинг фоизига кирмайди. Рейтингда фақат Verifixда лидер лавозимидагилар.",
      kindLabels: { acting: "Лидер ўрнида", none: "Лавозими аниқланмаган" },
    },
  },
  ru: {
    title: "Хавотиры работников",
    vRating: "Рейтинг", vList: "Список",
    loadFailed: "Не удалось загрузить данные",
    loadFailedMsg: "Сервер не ответил или пропала связь. Попробуйте ещё раз.",
    retry: "Повторить",
    errRange: "Неверный период: начало позже конца",
    errStats: "Не удалось загрузить сводку, бригадиров, ячейки и динамику",
    errLeaders: "Не удалось загрузить рейтинг лидеров", errList: "Не удалось загрузить список хавотиров",
    errOpen: "Не удалось загрузить открытые хавотиры", errMeta: "Не удалось загрузить данные страницы",
    fLeadersFailed: "Цифры по лидерам не загрузились",
    emptyTitle: "Хавотиров пока нет",
    emptyNote: "Здесь считаются хавотиры, которые работники пишут на странице «Хавотиры ячеек».",
    emptyGo: "Хавотиры ячеек",
    emptyPeriodTitle: "За этот период хавотиров нет",
    emptyPeriodMsg: "За выбранный период работники не писали хавотиров.",
    emptyPeriodFiltered: "Нет хавотиров за выбранный период с этими фильтрами.",
    showAllTime: "Показать за всё время",
    clearFilters: "Сбросить фильтры",
    hLabel: "Решённые хавотиры",
    hInfo: "Хавотиры, которые работники пишут лидерам на странице «Хавотиры ячеек». Каждый засчитывается лидеру, которому он подан: % = решено ÷ (всего − передано выше). Хавотир, переданный бригадиру или выше, в % лидера не входит — даже если его потом решили. В рейтинге только те, кто в Verifix на должности лидера. Работники считаются по введённому имени.",
    hOf: "Решено {done} из {total}",
    hOfRated: "Решено {done} из {rated}, оставшихся у лидера",
    hUpOut: "Ещё {u} передано выше — в % не входят",
    upDone: "решён выше",
    hPrevLead: "предыдущие {n} дн.", hPrevNoneTail: "хавотиров не было",
    hUp: "+{d} п.п.", hDown: "−{d} п.п.", hSame: "почти без изменений",
    hPrevTip: "{from} – {to}: {done} / {total} — на тот же срок после окончания периода",
    hLow: "мало данных — меньше 5 хавотиров",
    fWorkers: "Писавших работников: {n}",
    fWith: "Лидеров с хавотирами: {n}",
    fNone: "Лидеров без хавотиров: {n}",
    fUnassigned: "Хавотиров без лидера: {n} — вне рейтинга",
    rTitle: "Рейтинг лидеров",
    rSub: "по % решённых, лучшие сверху",
    rCount: "лидеров: {n}",
    rRanked: "в рейтинге: {k}", showMore: "Показать ещё {n}",
    rSearch: "Поиск лидера…",
    colRank: "#", colLeader: "Лидер", colStatuses: "Статусы", colTotal: "Всего",
    colOpen: "Открыто", colPct: "% решено", colOpenHint: "У лидера: новые + в работе", colPctHint: "% = решено ÷ (всего − передано выше)",
    gLow: "Мало данных — меньше 5 хавотиров, вне рейтинга",
    gNone: "Лидеры без хавотиров",
    gNotLeader: "Вне рейтинга — в Verifix не на должности лидера",
    kindActing: "Вместо лидера", kindNone: "Должность не определена",
    showNone: "Лидеров без хавотиров: {n} — показать",
    hideNone: "Скрыть лидеров без хавотиров",
    bandLowL: "n < {m}",
    bandsEdit: "Пороги", bandsTitle: "Пороги KPI",
    bandGreenL: "Зелёный порог (≥ %)", bandYellowL: "Жёлтый порог (≥ %)",
    bandsHint: "Ниже жёлтого — красный. Пороги общие для всей платформы.",
    bandsSaved: "Пороги сохранены", bandsErr: "Не удалось сохранить",
    noMatchLeaders: "Нет лидеров по запросу",
    uTitle: "Бригадиры",
    uSub: "по % решённых · нажмите — страница сузится до бригадира",
    uLeaders: "лидеров с хавотирами: {n}",
    cTitle: "Ячейки — нерешённые хавотиры",
    cSub: "ячейки с наибольшим числом открытых хавотиров",
    cMine: "Мои ячейки", cMineSub: "статус хавотиров по каждой ячейке",
    cNoOpen: "Открытых хавотиров у лидеров нет",
    cOpen: "откр.",
    dTitle: "Динамика по дням",
    dSub: "хавотиры, поступившие каждый день, и их текущий статус",
    dTitleWeek: "Динамика по неделям",
    dSubWeek: "хавотиры, поступившие за каждую неделю, и их текущий статус",
    dAxis: "хавотиров, шт.",
    myOpenTitle: "Ваши нерешённые хавотиры", myOpenSub: "сначала самые старые",
    myNoOpen: "Нерешённых хавотиров нет",
    myUpTitle: "У бригадира", myActTitle: "У вас", moreOf: "Показать ещё {n}",
    goAct: "Открыть в «Хавотирах ячеек»", seeAll: "Показать все",
    lmRank: "{r}-е место из {n} в рейтинге",
    lmUnranked: "Вне рейтинга — меньше 5 хавотиров",
    lmNotLeader: "Вне рейтинга — в Verifix не на должности лидера",
    lmNone: "За этот период этому лидеру не писали",
    lmOpenTitle: "Открытые у лидера", lmShowing: "Показано {k} из {n}",
    lmAll: "Все хавотиры лидера", lmCells: "Ячейки",
    ageToday: "сегодня", ageDays: "{n} дн.",
    regTitle: "Хавотиры", regSearch: "Текст, работник, лидер или №", regCount: "{n}",
    colNo: "№", colDate: "Дата", colCell: "Ячейка", colText: "Хавотир", colWorker: "Работник",
    colTextWho: "Хавотир · работник → лидер", colTextWorker: "Хавотир · работник",
    colStatus: "Статус",
    noMatch: "Ничего не найдено",
    mTitle: "Хавотир", mBrig: "Бригадир", mCategory: "Отдел", mStep: "Уровень",
    mDoneOn: "Дата решения", mOpen: "Открыть в «{page}»",
    close: "Закрыть", cancel: "Отмена", save: "Сохранить",
    fBrig: "Бригадир", fLeader: "Лидер", fCell: "Ячейка", fStatus: "Статус",
    gWho: "Кто и где", gWhat: "Статус",
    nByBrig: "Сужено по выбранному бригадиру · {n}",
    nByLeader: "Сужено по выбранному лидеру · {n}",
    widenBrig: "Показать всех бригадиров", widenLeader: "Показать всех лидеров",
    emptyList: "Нет вариантов для этого выбора",
    stUpHint: "Передан бригадиру (или выше) — в % лидера не входит, даже если потом решён",
    uNarrowed: "Страница сужена до бригадира {name} — снимите фильтр крестиком на чипе",
    rowTotOpen: "всего {t} · откр. {o}", rowTotUpOpen: "всего {t} · выше {u} · откр. {o}", cTotal: "всего {n}",
    hShort: "Короткий период ({n} дн.): новые хавотиры ещё не успели решить — цветом не оценивается",
    startTitle: "Данные начинаются с {date}",
    startMsg: "Работники пишут в «Хавотиры ячеек» с {date}.",
    startBtn: "Показать с {date}",
    xSub: "Опасения, которые работники пишут лидерам на странице «Хавотиры ячеек» — KPI лидеров",
    xBtn: "Excel", xTitle: "Экспорт в Excel",
    xModalQ: "Применены фильтры. Что включить в файл?",
    xOptFiltered: "Только отфильтрованные записи", xOptFilteredD: "Срез, который сейчас на экране",
    xOptAll: "Все данные за период", xOptAllD: "Полная картина за выбранный период — без фильтров",
    xExport: "Экспортировать", xDownloaded: "Файл скачан", xSentTg: "Файл отправлен в Telegram",
    xFailed: "Не удалось экспортировать",
    xPeriod: "Период", xPlant: "Завод", xAllPlants: "Все заводы",
    xFilters: "Фильтры", xScopeAll: "Все данные (без фильтров)",
    xGenerated: "Сформирован", xSearch: "Поиск",
    xSheets: { overview: "Обзор", leaders: "Рейтинг лидеров", register: "Хавотиры" },
    xLabels: {
      secKpi: "Ключевые показатели",
      kTotal: "Всего хавотиров", kResolved: "Решено", kDoing: "В работе",
      kOpen: "Открыто у лидера", kOpenHint: "новые + в работе",
      kWorkers: "Активных работников", kWorkersHint: "по введённому имени",
      secDaily: "Динамика по дням", secDailySub: "по статусам, дата подачи",
      secBrig: "Разрез по бригадирам", secBrigSub: "выбранный период, по статусам",
      secCells: "Ячейки — топ нерешённых", secCellsSub: "ячейки с наибольшим числом открытых хавотиров",
      secLeaders: "Рейтинг лидеров", secLeadersSub: "все лидеры — по лидеру, которому подан хавотир",
      secRegister: "Реестр хавотиров",
      colLeader: "Лидер", colBrig: "Бригадир", colCells: "Ячейки", colTotal: "Всего",
      colDone: "Решено", colDoing: "В работе", colOpen: "Открыто (у лидера)", colPct: "% решено",
      colDate: "Дата", colCell: "Ячейка", colOwner: "Работник", colText: "Хавотир", colStatus: "Статус",
      unassignedRow: "Хавотиры без лидера",
      lowNHint: "меньше 5 хавотиров — недостаточно для рейтинга", noMatch: "Ничего не найдено",
      rows: "строк", concernsWord: "хавотиров", leadersWord: "лидеров", kamBand: "мало данных",
      rateNote: "% = решено ÷ (всего − передано выше): хавотир, переданный выше, в % лидера не входит. В рейтинге только те, кто в Verifix на должности лидера.",
      kindLabels: { acting: "Вместо лидера", none: "Должность не определена" },
    },
  },
  en: {
    title: "Worker concerns",
    vRating: "Ranking", vList: "List",
    loadFailed: "Failed to load data",
    loadFailedMsg: "The server did not answer or the connection dropped. Try again.",
    retry: "Retry",
    errRange: "Invalid period: the start is after the end",
    errStats: "Couldn't load the summary, brigadirs, cells and trend",
    errLeaders: "Couldn't load the leader ranking", errList: "Couldn't load the list of concerns",
    errOpen: "Couldn't load the open concerns", errMeta: "Couldn't load the page data",
    fLeadersFailed: "Leader figures didn't load",
    emptyTitle: "No concerns yet",
    emptyNote: "Concerns workers write on the «Cell concerns» page are counted here.",
    emptyGo: "Cell concerns",
    emptyPeriodTitle: "No concerns in this period",
    emptyPeriodMsg: "Workers wrote no concerns in the selected period.",
    emptyPeriodFiltered: "No concerns match the selected period and filters.",
    showAllTime: "Show all time",
    clearFilters: "Clear filters",
    hLabel: "Concerns resolved",
    hInfo: "Concerns workers write to their leaders on the «Cell concerns» page. Each counts for the leader it was filed to: % = resolved ÷ (total − escalated). A concern escalated to the brigadir or higher is out of the leader's % — even if it was resolved later. Only leaders by their Verifix job are ranked. Workers are counted by the name typed.",
    hOf: "{done} of {total} resolved",
    hOfRated: "{done} of {rated} kept by the leader resolved",
    hUpOut: "{u} more escalated — not in the %",
    upDone: "resolved above",
    hPrevLead: "previous {n} days", hPrevNoneTail: "no concerns",
    hUp: "+{d} pts", hDown: "−{d} pts", hSame: "about the same",
    hPrevTip: "{from} – {to}: {done} / {total}, as it stood the same time after that period ended",
    hLow: "low data — fewer than 5 concerns",
    fWorkers: "Workers who wrote: {n}",
    fWith: "Leaders with concerns: {n}",
    fNone: "Leaders with none: {n}",
    fUnassigned: "Concerns with no leader: {n} — not ranked",
    rTitle: "Leader ranking",
    rSub: "by % resolved, best first",
    rCount: "leaders: {n}",
    rRanked: "{k} ranked", showMore: "Show {n} more",
    rSearch: "Search leaders…",
    colRank: "#", colLeader: "Leader", colStatuses: "Statuses", colTotal: "Total",
    colOpen: "Open", colPct: "% resolved", colOpenHint: "With the leader: new + in progress", colPctHint: "% = resolved ÷ (total − escalated)",
    gLow: "Low data — fewer than 5 concerns, not ranked",
    gNone: "Leaders with no concerns",
    gNotLeader: "Not ranked — not a leader by their Verifix job",
    kindActing: "In place of a leader", kindNone: "Role not determined",
    showNone: "Leaders with no concerns: {n} — show",
    hideNone: "Hide leaders with no concerns",
    bandLowL: "n < {m}",
    bandsEdit: "Thresholds", bandsTitle: "KPI thresholds",
    bandGreenL: "Green threshold (≥ %)", bandYellowL: "Yellow threshold (≥ %)",
    bandsHint: "Below yellow counts as red. Thresholds are platform-wide.",
    bandsSaved: "Thresholds saved", bandsErr: "Could not save",
    noMatchLeaders: "No leader matches the search",
    uTitle: "Brigadirs",
    uSub: "by % resolved · tap one to narrow the page to that brigadir",
    uLeaders: "leaders written to: {n}",
    cTitle: "Cells — unresolved concerns",
    cSub: "cells with the most open concerns",
    cMine: "My cells", cMineSub: "concern status in each of your cells",
    cNoOpen: "No concerns open with the leaders",
    cOpen: "open",
    dTitle: "Daily trend",
    dSub: "concerns filed each day and where they stand now",
    dTitleWeek: "Weekly trend",
    dSubWeek: "concerns filed each week and where they stand now",
    dAxis: "concerns",
    myOpenTitle: "Your unresolved concerns", myOpenSub: "oldest first",
    myNoOpen: "No unresolved concerns",
    myUpTitle: "With the brigadir", myActTitle: "With you", moreOf: "Show {n} more",
    goAct: "Open in «Cell concerns»", seeAll: "See all",
    lmRank: "rank {r} of {n} ranked",
    lmUnranked: "Not ranked — fewer than 5 concerns",
    lmNotLeader: "Not ranked — not a leader by their Verifix job",
    lmNone: "No concerns were filed to this leader in this period",
    lmOpenTitle: "Open with the leader", lmShowing: "Showing {k} of {n}",
    lmAll: "All of this leader's concerns", lmCells: "Cells",
    ageToday: "today", ageDays: "{n} d",
    regTitle: "Concerns", regSearch: "Text, worker, leader or №", regCount: "{n}",
    colNo: "№", colDate: "Date", colCell: "Cell", colText: "Concern", colWorker: "Worker",
    colTextWho: "Concern · worker → leader", colTextWorker: "Concern · worker",
    colStatus: "Status",
    noMatch: "No match",
    mTitle: "Concern", mBrig: "Brigadir", mCategory: "Department", mStep: "Chain step",
    mDoneOn: "Resolved on", mOpen: "Open in «{page}»",
    close: "Close", cancel: "Cancel", save: "Save",
    fBrig: "Brigadir", fLeader: "Leader", fCell: "Cell", fStatus: "Status",
    gWho: "Who and where", gWhat: "Status",
    nByBrig: "Narrowed by the picked brigadir · {n}",
    nByLeader: "Narrowed by the picked leader · {n}",
    widenBrig: "Show every brigadir", widenLeader: "Show every leader",
    emptyList: "Nothing to pick for this choice",
    stUpHint: "Handed to the brigadir (or higher) — out of the leader's %, even if resolved later",
    uNarrowed: "Page narrowed to {name} — remove it with × on the filter chip",
    rowTotOpen: "total {t} · open {o}", rowTotUpOpen: "total {t} · escalated {u} · open {o}", cTotal: "total {n}",
    hShort: "Short period ({n} days): new concerns haven't had time to be resolved — not colour-graded",
    startTitle: "Records start on {date}",
    startMsg: "Workers began filing on «Cell concerns» on {date}.",
    startBtn: "Show from {date}",
    xSub: "Concerns workers write to their leaders on «Cell concerns» — the leaders' KPI",
    xBtn: "Excel", xTitle: "Excel export",
    xModalQ: "Filters are applied. What should go into the file?",
    xOptFiltered: "Only the filtered records", xOptFilteredD: "The slice currently on screen",
    xOptAll: "All data for the period", xOptAllD: "The full picture for the selected range — no filters",
    xExport: "Export", xDownloaded: "File downloaded", xSentTg: "File sent to Telegram",
    xFailed: "Export failed",
    xPeriod: "Period", xPlant: "Plant", xAllPlants: "All plants",
    xFilters: "Filters", xScopeAll: "All data (no filters)",
    xGenerated: "Generated", xSearch: "Search",
    xSheets: { overview: "Overview", leaders: "Leader ranking", register: "Concerns" },
    xLabels: {
      secKpi: "Key figures",
      kTotal: "Total concerns", kResolved: "Resolved", kDoing: "In progress",
      kOpen: "Open with leaders", kOpenHint: "new + in progress",
      kWorkers: "Active workers", kWorkersHint: "by the name typed",
      secDaily: "Daily trend", secDailySub: "by status, filing date",
      secBrig: "By brigadir", secBrigSub: "selected period, by status",
      secCells: "Cells — top unresolved", secCellsSub: "cells with the most open concerns",
      secLeaders: "Leader ranking", secLeadersSub: "every leader — by the leader each concern was filed to",
      secRegister: "Concerns register",
      colLeader: "Leader", colBrig: "Brigadir", colCells: "Cells", colTotal: "Total",
      colDone: "Resolved", colDoing: "In progress", colOpen: "Open (with leader)", colPct: "% resolved",
      colDate: "Date", colCell: "Cell", colOwner: "Worker", colText: "Concern", colStatus: "Status",
      unassignedRow: "Concerns with no leader",
      lowNHint: "fewer than 5 concerns — not enough to rank", noMatch: "No match",
      rows: "rows", concernsWord: "concerns", leadersWord: "leaders", kamBand: "low data",
      rateNote: "% = resolved ÷ (total − escalated): a concern escalated higher is out of the leader's %. Only leaders by their Verifix job are ranked.",
      kindLabels: { acting: "In place of a leader", none: "Role not determined" },
    },
  },
};
