import { useLang } from "../../context/LangContext";

/* Every word the «Chek-list» tab and its task sheet say, in the platform's four
 * languages. One module for both, because the row and the sheet it opens must
 * call a state by the same name — a row reading «Rad etildi» over a sheet
 * headed «Qabul qilinmadi» is two answers to one question. */

export const CL_T = {
  uz: {
    mine: "Mening chek-listim", readOnly: "Faqat ko'rish uchun — vazifalarni lider o'zi topshiradi.",
    pickT: "Liderni tanlang",
    pickM: "Kunini ko'rish uchun yuqoridagi «Lider» filtridan liderni tanlang.",
    pickHere: "Kunini ko'rish uchun quyidagi ro'yxatdan liderni tanlang.",
    noCellT: "Yacheyka biriktirilmagan",
    noCellMine: "Brigadangizda chek-list har bir yacheyka uchun alohida topshiriladi, sizga esa hali yacheyka biriktirilmagan. Brigadiringizga murojaat qiling.",
    noCellOther: "Bu brigadada chek-list har bir yacheyka uchun alohida topshiriladi, bu liderga esa yacheyka biriktirilmagan — u hech narsa topshirmaydi.",
    noLoadT: "Chek-list talab qilinmaydi",
    noLoadMine: "Yacheykalaringizdan hech biri zagruzkada hisoblanmaydi va oktabrda hech narsa topshirmagansiz — sizdan kunlik chek-list talab qilinmaydi va siz reytingga kirmaysiz. Yacheykangiz zagruzkaga qo'shilsa, chek-list shu yerda paydo bo'ladi.",
    noLoadOther: "Bu liderning yacheykalaridan hech biri zagruzkada hisoblanmaydi va u oktabrda hech narsa topshirmagan — undan kunlik chek-list talab qilinmaydi va u reytingga kirmaydi.",
    photoFailed: "Rasm yuklanmadi", failedT: "Chek-listni yuklab bo'lmadi", failedM: "Internetni tekshirib, qayta urinib ko'ring.", retry: "Qayta urinish",
    runningLbl: "Hozirgi ball", runningNote: "Faqat tekshirilgan vazifalar hisoblanadi · jami {total}",
    submittedOf: "{n} / {total} topshirildi", resultLbl: "Kun natijasi", rawLbl: "Topshirilgan: {raw}%",
    legDone: "Qabul qilindi", legChecking: "Tekshirilmoqda", legFailed: "O'tmadi", legTodo: "Qoldi",
    nextLbl: "Keyingi muddat", nextLine: "№{id} · {time} gacha",
    dayClosedToday: "Kun yopilgan — natija yakuniy.",
    nothingT: "Bu kun chek-list topshirilmagan", nothingM: "Hech bir vazifa bo'yicha javob yozilmagan.",
    sheetNote: "Bu kun Google-forma orqali topshirilgan — faqat natija ko'rinadi.",
    rehearsalNote: "Mashq kuni — bu bot topshiruvi natijaga kirmaydi.",
    excludedNote: "Bu kun natijalarga kirmaydi.", voidedNote: "Kun vaqtida yuborilmagan — 0% bilan hisoblanadi.",
    closeDay: "Kunni yopish", closeDayNeed: "Kunni yopish uchun barcha vazifalarga javob bering — {n} ta qoldi.",
    closeDayT: "Kun yopilsinmi?", closeDayM: "Yopilgandan keyin javoblarni o'zgartirib bo'lmaydi. Rasmlar AI tekshiruviga yuboriladi.",
    closeDayOk: "Kun yopildi — natija: {score}%",
    gTodo: "Qilish kerak", gRejected: "Rad etildi", gFailed: "Bajarilmadi", gChecking: "Tekshirilmoqda", gDone: "Qabul qilindi",
    show: "Ko'rsatish", hide: "Yashirish",
    by: "{time} gacha", left: "{t} qoldi", mins: "{m} daq", hours: "{h} soat {m} daq",
    opens: "{time} dan ochiladi", timeUp: "Vaqt tugadi", draft: "Javob berilgan — topshirilmagan",
    savedDay: "Javob saqlandi — kun yopilganda topshiriladi",
    bDraftDayT: "Javob saqlandi", bDraftDayM: "Kunni yopganingizda topshiriladi. Unga qadar javobni qaytadan boshlash mumkin.",
    camRoll: "Kamerada {k}/{n}", autoAt: "Tizim {time} da tekshiradi", checking: "AI tekshirmoqda…",
    accepted: "Qabul qilindi", byAdmin: "Admin qabul qildi", submittedAt: "{time} da topshirilgan",
    expired: "{time} gacha topshirilmadi", notdone: "Bajarilmadi", missing: "Hech narsa topshirilmagan",
    ruledout: "Admin: bajarilmagan", autoPassed: "Tizim tasdiqladi", autoFailed: "Tekshiruvdan o'tmadi",
    flagged: "AI qabul qilmadi",
    kindCam: "Kamera", kindShot: "Rasm", kindAuto: "Avtomatik", kindNone: "Rasmsiz",
    object: "E'tiroz bildirish", late: "Kechikkan isbot", submit: "Topshirish", openChat: "Chatni ochish",
    yourTurn: "Sizning navbatingiz",
    dSup: "E'tiroz — brigadirda", dAdm: "E'tiroz — adminlarda", dOk: "E'tiroz qabul qilindi",
    dNo: "E'tiroz rad etildi", dCancel: "E'tiroz bekor qilingan",
    lSup: "Kechikkan isbot — brigadirda", lAdm: "Kechikkan isbot — adminlarda",
    lOk: "Kechikkan isbot qabul qilindi", lNo: "Kechikkan isbot rad etildi",
    st_open: "Bajarilmagan", st_draft: "Topshirilmagan", st_pending: "Tekshirilmoqda", st_passed: "Qabul qilindi",
    st_rejected: "Rad etildi", st_expired: "Vaqti o'tdi", st_notdone: "Bajarilmadi", st_missing: "Topshirilmagan",
    st_autopass: "Tizim tasdiqladi", st_autofail: "Tekshiruvdan o'tmadi", st_ruledout: "Admin: bajarilmagan",
    bPendingT: "AI rasmlarni tekshirmoqda", bPendingM: "Odatda bir necha daqiqa. Natija shu yerda o'zi paydo bo'ladi.",
    bPassedT: "Vazifa qabul qilindi", bPassedAdminT: "Admin vazifani bajarilgan deb hisobladi",
    bRejectedT: "AI rasmni qabul qilmadi", bRejectedM: "Bu vazifa uchun ball berilmaydi. Qaror noto'g'ri bo'lsa, e'tiroz bildiring.",
    bAutoFailT: "Avtomatik tekshiruvdan o'tmadi", bAutoFailM: "Tekshiruv noto'g'ri bo'lsa, e'tiroz bildiring.",
    bAutoPassT: "Avtomatik tekshiruvdan o'tdi",
    bExpiredT: "Muddat o'tib ketdi", bExpiredM: "Soat {time} gacha topshirilmadi.",
    bNotdoneT: "«Bajarilmadi» deb topshirilgan", bMissingT: "Bu vazifa topshirilmagan",
    bRuledoutT: "Admin bajarilmagan deb hisobladi",
    bDraftT: "Javob saqlangan, lekin hali topshirilmagan",
    bDraftM: "Topshirmaguningizcha ball hisoblanmaydi. Muddat tugaganda tizim uni o'zi topshiradi.",
    bNotStartedT: "Bu vazifa soat {time} dan ochiladi", bNotStartedM: "Undan oldin olingan rasm rad etiladi.",
    bTimeUpT: "Vaqt tugadi", bTimeUpM: "Soat {time} dan keyin vazifani odatdagidek topshirib bo'lmaydi — faqat kechikkan isbot.",
    ruleDeadline: "Topshirish", ruleWindow: "Rasm vaqti", ruleWindowV: "{from}–{to}",
    ruleDay: "Rasmda bugungi sana ko'rinsin", ruleTime: "Rasmdagi soat: {from}–{to}", ruleNone: "Sana tekshirilmaydi",
    ruleWeight: "Ulush", rulePhotos: "Rasmlar", rulePhotosV: "kamida {n} ta",
    howTo: "Qanday bajariladi", examples: "Namuna", more: "Batafsil", less: "Qisqaroq",
    q: "Vazifa bajarildimi?", yes: "Bajarildi", no: "Bajarilmadi",
    photosLbl: "Isbot rasmlari", photosNeed: "Kamida {n} ta, ko'pi bilan {max} ta",
    dropLabel: "Rasm tanlash", dropActive: "Qo'yib yuboring", dropBusy: "Yuklanmoqda…",
    dropHint: "Kompyuterda skrinshotni Ctrl+V bilan ham qo'yishingiz mumkin.",
    notImage: "Faqat rasm yuklash mumkin", removePhoto: "Rasmni olib tashlash", tooMany: "Ko'pi bilan {max} ta rasm",
    reasonLbl: "Nega bajarilmadi?", reasonPh: "Qisqacha yozing — brigadir va admin o'qiydi",
    camT: "Bu vazifa ilovadagi kamera bilan olinadi",
    camM: "Galereyadan rasm yuklab bo'lmaydi — suratga olish vaqti tizim tomonidan belgilanadi.",
    camOpen: "Kamerani ochish", camMore: "Suratga olishni davom ettirish", camHave: "Olingan: {k} / {n}",
    camReady: "Rasmlar tayyor — endi topshiring", noProof: "Bu vazifa uchun rasm talab qilinmaydi.",
    submitT: "Vazifa topshirilsinmi?",
    submitM: "Topshirilgandan keyin javobni o'zgartirib bo'lmaydi. AI rasmlarni odatda bir necha daqiqada tekshiradi — natija shu yerda chiqadi.",
    submitNoM: "Vazifa «bajarilmadi» deb topshiriladi — bu vazifa uchun ball berilmaydi. Keyin o'zgartirib bo'lmaydi.",
    submitOk: "Topshirildi — AI tekshirmoqda", submitNoOk: "Topshirildi", saveOk: "Saqlandi",
    save: "Saqlash", cancel: "Bekor qilish", close: "Yopish",
    restart: "Qayta boshlash", restartT: "Javob o'chirilsinmi?",
    restartM: "Bu vazifadagi javob va rasmlar o'chiriladi — keyin qaytadan topshirasiz.", restartOk: "Javob o'chirildi",
    answerLbl: "Javob", evidence: "Isbot", reasonShown: "Sabab",
    objT: "E'tiroz",
    objIntro: "Qaror noto'g'ri bo'lsa, sababini yozing. Brigadiringiz o'qiydi: rad etadi yoki adminlarga yuboradi. Ball faqat admin qaroridan keyin qaytadi.",
    objIntroAuto: "Tekshiruv noto'g'ri bo'lsa (masalan, ma'lumot vaqtida kiritilgan edi), sababini yozing. Brigadiringiz o'qiydi, keyin adminlar hal qiladi.",
    objPh: "Masalan: rasmda soat aniq ko'rinib turibdi", objPhAuto: "Masalan: reja soat 9:40 da kiritilgan edi",
    objEmpty: "E'tirozingiz brigadir va adminlar bilan chat bo'lib ochiladi.",
    objSent: "E'tiroz yuborildi — brigadir ko'rib chiqadi",
    lateT: "Kechikkan isbot",
    lateIntro: "Muddat o'tdi, shuning uchun bu isbot o'z-o'zidan ball bermaydi. Sababingizni avval brigadir, keyin admin o'qiydi — qabul qilishsa, vazifa to'liq hisoblanadi.",
    lateOpen: "Kechikkan isbot yuborish", lateReason: "Nega kechikdingiz?", lateReasonPh: "Masalan: telefon o'chib qolgan edi",
    lateCam: "Ilovada suratga olish", lateShot: "Kamerada olingan: {n}", lateSend: "Yuborish",
    lateOk: "Kechikkan isbot yuborildi — brigadir ko'rib chiqadi", latePhotosLbl: "Rasmlar", lateNeed: "Kamida bitta rasm kerak",
    autoT: "Bu vazifani tizim o'zi tekshiradi",
    autoM: "Soat {time} da tizim ma'lumotni o'qiydi — rasm yuborish shart emas. Ishni o'z sahifasida vaqtida bajaring.",
    autoLive: "Hozirgi holat", autoLiveErr: "Hozirgi holatni o'qib bo'lmadi",
    lvPlan: "Reja kiritilgan pozitsiyalar: {a} / {b}", lvUntyped: "Odamlar soni kiritilmagan: {codes}",
    lvPeopleOk: "Odamlar soni kiritilgan", lvPct: "Bajarilishi: {pct}% (maqsad {target}%)",
    lvConcerns: "Bugun yozilgan xavotirlar: {n} ta", lvNoSap: "Yacheykada SAP kodi yo'q — adminlar tuzatadi",
    adminT: "Admin", admReopen: "Qayta ochish", admEmpty: "Tozalash",
    admReopenT: "Vazifa qayta ochilsinmi?",
    admReopenM: "Lider uni qaytadan topshira oladi. AI xulosasi o'chiriladi va kun bahosi qayta hisoblanadi.",
    admEmptyT: "Vazifa tozalansinmi?", admEmptyM: "Javob va rasmlar o'chiriladi, vazifa qayta ochiladi.",
    admOk: "Vazifa qayta ochildi", admEmptyOk: "Vazifa tozalandi",
    tPassed: "№{id} qabul qilindi", tRejected: "№{id} rad etildi — e'tiroz bildirishingiz mumkin",
    missedLine: "Soat {time} gacha topshirilmadi.",
    e_time_up: "Vaqt tugadi — endi faqat kechikkan isbot yuborish mumkin.", e_locked: "Bu vazifa allaqachon topshirilgan.",
    e_day_closed: "Kun yopilgan.", e_camera_task: "Bu vazifa faqat ilovadagi kamera bilan olinadi.",
    e_auto_task: "Bu vazifani tizim o'zi tekshiradi.", e_need_photos: "Rasmlar yetarli emas.",
    e_too_many_photos: "Rasmlar juda ko'p.", e_reason_required: "Sababni yozing (kamida 3 ta belgi).",
    e_invalid_image: "Bu fayl rasm emas yoki uni o'qib bo'lmadi.", e_too_large: "Rasm juda katta (10 MB gacha).",
    e_relay_failed: "Rasmni saqlab bo'lmadi — qayta urinib ko'ring.", e_late_gone: "Kechikkan isbot yuborish muddati tugagan.",
    e_incomplete: "Vazifa hali to'liq emas.", e_pick_cell: "Yacheykani tanlang.",
    e_no_load: "Sizdan chek-list talab qilinmaydi — yacheykalaringiz zagruzkada hisoblanmaydi.",
    e_generic: "Saqlab bo'lmadi — qayta urinib ko'ring.",
  },
  uz_cyrl: {
    mine: "Менинг чек-листим", readOnly: "Фақат кўриш учун — вазифаларни лидер ўзи топширади.",
    pickT: "Лидерни танланг",
    pickM: "Кунини кўриш учун юқоридаги «Лидер» фильтридан лидерни танланг.",
    pickHere: "Кунини кўриш учун қуйидаги рўйхатдан лидерни танланг.",
    noCellT: "Ячейка бириктирилмаган",
    noCellMine: "Бригадангизда чек-лист ҳар бир ячейка учун алоҳида топширилади, сизга эса ҳали ячейка бириктирилмаган. Бригадирингизга мурожаат қилинг.",
    noCellOther: "Бу бригадада чек-лист ҳар бир ячейка учун алоҳида топширилади, бу лидерга эса ячейка бириктирилмаган — у ҳеч нарса топширмайди.",
    noLoadT: "Чек-лист талаб қилинмайди",
    noLoadMine: "Ячейкаларингиздан ҳеч бири загрузкада ҳисобланмайди ва октябрда ҳеч нарса топширмагансиз — сиздан кунлик чек-лист талаб қилинмайди ва сиз рейтингга кирмайсиз. Ячейкангиз загрузкага қўшилса, чек-лист шу ерда пайдо бўлади.",
    noLoadOther: "Бу лидернинг ячейкаларидан ҳеч бири загрузкада ҳисобланмайди ва у октябрда ҳеч нарса топширмаган — ундан кунлик чек-лист талаб қилинмайди ва у рейтингга кирмайди.",
    photoFailed: "Расм юкланмади", failedT: "Чек-листни юклаб бўлмади", failedM: "Интернетни текшириб, қайта уриниб кўринг.", retry: "Қайта уриниш",
    runningLbl: "Ҳозирги балл", runningNote: "Фақат текширилган вазифалар ҳисобланади · жами {total}",
    submittedOf: "{n} / {total} топширилди", resultLbl: "Кун натижаси", rawLbl: "Топширилган: {raw}%",
    legDone: "Қабул қилинди", legChecking: "Текширилмоқда", legFailed: "Ўтмади", legTodo: "Қолди",
    nextLbl: "Кейинги муддат", nextLine: "№{id} · {time} гача",
    dayClosedToday: "Кун ёпилган — натижа якуний.",
    nothingT: "Бу кун чек-лист топширилмаган", nothingM: "Ҳеч бир вазифа бўйича жавоб ёзилмаган.",
    sheetNote: "Бу кун Google-форма орқали топширилган — фақат натижа кўринади.",
    rehearsalNote: "Машқ куни — бу бот топшируви натижага кирмайди.",
    excludedNote: "Бу кун натижаларга кирмайди.", voidedNote: "Кун вақтида юборилмаган — 0% билан ҳисобланади.",
    closeDay: "Кунни ёпиш", closeDayNeed: "Кунни ёпиш учун барча вазифаларга жавоб беринг — {n} та қолди.",
    closeDayT: "Кун ёпилсинми?", closeDayM: "Ёпилгандан кейин жавобларни ўзгартириб бўлмайди. Расмлар AI текширувига юборилади.",
    closeDayOk: "Кун ёпилди — натижа: {score}%",
    gTodo: "Қилиш керак", gRejected: "Рад этилди", gFailed: "Бажарилмади", gChecking: "Текширилмоқда", gDone: "Қабул қилинди",
    show: "Кўрсатиш", hide: "Яшириш",
    by: "{time} гача", left: "{t} қолди", mins: "{m} дақ", hours: "{h} соат {m} дақ",
    opens: "{time} дан очилади", timeUp: "Вақт тугади", draft: "Жавоб берилган — топширилмаган",
    savedDay: "Жавоб сақланди — кун ёпилганда топширилади",
    bDraftDayT: "Жавоб сақланди", bDraftDayM: "Кунни ёпганингизда топширилади. Унга қадар жавобни қайтадан бошлаш мумкин.",
    camRoll: "Камерада {k}/{n}", autoAt: "Тизим {time} да текширади", checking: "AI текширмоқда…",
    accepted: "Қабул қилинди", byAdmin: "Админ қабул қилди", submittedAt: "{time} да топширилган",
    expired: "{time} гача топширилмади", notdone: "Бажарилмади", missing: "Ҳеч нарса топширилмаган",
    ruledout: "Админ: бажарилмаган", autoPassed: "Тизим тасдиқлади", autoFailed: "Текширувдан ўтмади",
    flagged: "AI қабул қилмади",
    kindCam: "Камера", kindShot: "Расм", kindAuto: "Автоматик", kindNone: "Расмсиз",
    object: "Эътироз билдириш", late: "Кечиккан исбот", submit: "Топшириш", openChat: "Чатни очиш",
    yourTurn: "Сизнинг навбатингиз",
    dSup: "Эътироз — бригадирда", dAdm: "Эътироз — админларда", dOk: "Эътироз қабул қилинди",
    dNo: "Эътироз рад этилди", dCancel: "Эътироз бекор қилинган",
    lSup: "Кечиккан исбот — бригадирда", lAdm: "Кечиккан исбот — админларда",
    lOk: "Кечиккан исбот қабул қилинди", lNo: "Кечиккан исбот рад этилди",
    st_open: "Бажарилмаган", st_draft: "Топширилмаган", st_pending: "Текширилмоқда", st_passed: "Қабул қилинди",
    st_rejected: "Рад этилди", st_expired: "Вақти ўтди", st_notdone: "Бажарилмади", st_missing: "Топширилмаган",
    st_autopass: "Тизим тасдиқлади", st_autofail: "Текширувдан ўтмади", st_ruledout: "Админ: бажарилмаган",
    bPendingT: "AI расмларни текширмоқда", bPendingM: "Одатда бир неча дақиқа. Натижа шу ерда ўзи пайдо бўлади.",
    bPassedT: "Вазифа қабул қилинди", bPassedAdminT: "Админ вазифани бажарилган деб ҳисоблади",
    bRejectedT: "AI расмни қабул қилмади", bRejectedM: "Бу вазифа учун балл берилмайди. Қарор нотўғри бўлса, эътироз билдиринг.",
    bAutoFailT: "Автоматик текширувдан ўтмади", bAutoFailM: "Текширув нотўғри бўлса, эътироз билдиринг.",
    bAutoPassT: "Автоматик текширувдан ўтди",
    bExpiredT: "Муддат ўтиб кетди", bExpiredM: "Соат {time} гача топширилмади.",
    bNotdoneT: "«Бажарилмади» деб топширилган", bMissingT: "Бу вазифа топширилмаган",
    bRuledoutT: "Админ бажарилмаган деб ҳисоблади",
    bDraftT: "Жавоб сақланган, лекин ҳали топширилмаган",
    bDraftM: "Топширмагунингизча балл ҳисобланмайди. Муддат тугаганда тизим уни ўзи топширади.",
    bNotStartedT: "Бу вазифа соат {time} дан очилади", bNotStartedM: "Ундан олдин олинган расм рад этилади.",
    bTimeUpT: "Вақт тугади", bTimeUpM: "Соат {time} дан кейин вазифани одатдагидек топшириб бўлмайди — фақат кечиккан исбот.",
    ruleDeadline: "Топшириш", ruleWindow: "Расм вақти", ruleWindowV: "{from}–{to}",
    ruleDay: "Расмда бугунги сана кўринсин", ruleTime: "Расмдаги соат: {from}–{to}", ruleNone: "Сана текширилмайди",
    ruleWeight: "Улуш", rulePhotos: "Расмлар", rulePhotosV: "камида {n} та",
    howTo: "Қандай бажарилади", examples: "Намуна", more: "Батафсил", less: "Қисқароқ",
    q: "Вазифа бажарилдими?", yes: "Бажарилди", no: "Бажарилмади",
    photosLbl: "Исбот расмлари", photosNeed: "Камида {n} та, кўпи билан {max} та",
    dropLabel: "Расм танлаш", dropActive: "Қўйиб юборинг", dropBusy: "Юкланмоқда…",
    dropHint: "Компьютерда скриншотни Ctrl+V билан ҳам қўйишингиз мумкин.",
    notImage: "Фақат расм юклаш мумкин", removePhoto: "Расмни олиб ташлаш", tooMany: "Кўпи билан {max} та расм",
    reasonLbl: "Нега бажарилмади?", reasonPh: "Қисқача ёзинг — бригадир ва админ ўқийди",
    camT: "Бу вазифа иловадаги камера билан олинади",
    camM: "Галереядан расм юклаб бўлмайди — суратга олиш вақти тизим томонидан белгиланади.",
    camOpen: "Камерани очиш", camMore: "Суратга олишни давом эттириш", camHave: "Олинган: {k} / {n}",
    camReady: "Расмлар тайёр — энди топширинг", noProof: "Бу вазифа учун расм талаб қилинмайди.",
    submitT: "Вазифа топширилсинми?",
    submitM: "Топширилгандан кейин жавобни ўзгартириб бўлмайди. AI расмларни одатда бир неча дақиқада текширади — натижа шу ерда чиқади.",
    submitNoM: "Вазифа «бажарилмади» деб топширилади — бу вазифа учун балл берилмайди. Кейин ўзгартириб бўлмайди.",
    submitOk: "Топширилди — AI текширмоқда", submitNoOk: "Топширилди", saveOk: "Сақланди",
    save: "Сақлаш", cancel: "Бекор қилиш", close: "Ёпиш",
    restart: "Қайта бошлаш", restartT: "Жавоб ўчирилсинми?",
    restartM: "Бу вазифадаги жавоб ва расмлар ўчирилади — кейин қайтадан топширасиз.", restartOk: "Жавоб ўчирилди",
    answerLbl: "Жавоб", evidence: "Исбот", reasonShown: "Сабаб",
    objT: "Эътироз",
    objIntro: "Қарор нотўғри бўлса, сабабини ёзинг. Бригадирингиз ўқийди: рад этади ёки админларга юборади. Балл фақат админ қароридан кейин қайтади.",
    objIntroAuto: "Текширув нотўғри бўлса (масалан, маълумот вақтида киритилган эди), сабабини ёзинг. Бригадирингиз ўқийди, кейин админлар ҳал қилади.",
    objPh: "Масалан: расмда соат аниқ кўриниб турибди", objPhAuto: "Масалан: режа соат 9:40 да киритилган эди",
    objEmpty: "Эътирозингиз бригадир ва админлар билан чат бўлиб очилади.",
    objSent: "Эътироз юборилди — бригадир кўриб чиқади",
    lateT: "Кечиккан исбот",
    lateIntro: "Муддат ўтди, шунинг учун бу исбот ўз-ўзидан балл бермайди. Сабабингизни аввал бригадир, кейин админ ўқийди — қабул қилишса, вазифа тўлиқ ҳисобланади.",
    lateOpen: "Кечиккан исбот юбориш", lateReason: "Нега кечикдингиз?", lateReasonPh: "Масалан: телефон ўчиб қолган эди",
    lateCam: "Иловада суратга олиш", lateShot: "Камерада олинган: {n}", lateSend: "Юбориш",
    lateOk: "Кечиккан исбот юборилди — бригадир кўриб чиқади", latePhotosLbl: "Расмлар", lateNeed: "Камида битта расм керак",
    autoT: "Бу вазифани тизим ўзи текширади",
    autoM: "Соат {time} да тизим маълумотни ўқийди — расм юбориш шарт эмас. Ишни ўз саҳифасида вақтида бажаринг.",
    autoLive: "Ҳозирги ҳолат", autoLiveErr: "Ҳозирги ҳолатни ўқиб бўлмади",
    lvPlan: "Режа киритилган позициялар: {a} / {b}", lvUntyped: "Одамлар сони киритилмаган: {codes}",
    lvPeopleOk: "Одамлар сони киритилган", lvPct: "Бажарилиши: {pct}% (мақсад {target}%)",
    lvConcerns: "Бугун ёзилган хавотирлар: {n} та", lvNoSap: "Ячейкада SAP коди йўқ — админлар тузатади",
    adminT: "Админ", admReopen: "Қайта очиш", admEmpty: "Тозалаш",
    admReopenT: "Вазифа қайта очилсинми?",
    admReopenM: "Лидер уни қайтадан топшира олади. AI хулосаси ўчирилади ва кун баҳоси қайта ҳисобланади.",
    admEmptyT: "Вазифа тозалансинми?", admEmptyM: "Жавоб ва расмлар ўчирилади, вазифа қайта очилади.",
    admOk: "Вазифа қайта очилди", admEmptyOk: "Вазифа тозаланди",
    tPassed: "№{id} қабул қилинди", tRejected: "№{id} рад этилди — эътироз билдиришингиз мумкин",
    missedLine: "Соат {time} гача топширилмади.",
    e_time_up: "Вақт тугади — энди фақат кечиккан исбот юбориш мумкин.", e_locked: "Бу вазифа аллақачон топширилган.",
    e_day_closed: "Кун ёпилган.", e_camera_task: "Бу вазифа фақат иловадаги камера билан олинади.",
    e_auto_task: "Бу вазифани тизим ўзи текширади.", e_need_photos: "Расмлар етарли эмас.",
    e_too_many_photos: "Расмлар жуда кўп.", e_reason_required: "Сабабни ёзинг (камида 3 та белги).",
    e_invalid_image: "Бу файл расм эмас ёки уни ўқиб бўлмади.", e_too_large: "Расм жуда катта (10 MB гача).",
    e_relay_failed: "Расмни сақлаб бўлмади — қайта уриниб кўринг.", e_late_gone: "Кечиккан исбот юбориш муддати тугаган.",
    e_incomplete: "Вазифа ҳали тўлиқ эмас.", e_pick_cell: "Ячейкани танланг.",
    e_no_load: "Сиздан чек-лист талаб қилинмайди — ячейкаларингиз загрузкада ҳисобланмайди.",
    e_generic: "Сақлаб бўлмади — қайта уриниб кўринг.",
  },
  ru: {
    mine: "Мой чек-лист", readOnly: "Только просмотр — задачи сдаёт сам лидер.",
    pickT: "Выберите лидера",
    pickM: "Выберите лидера в фильтре «Лидер» выше, чтобы увидеть его день.",
    pickHere: "Выберите лидера в списке ниже, чтобы увидеть его день.",
    noCellT: "Ячейка не назначена",
    noCellMine: "В вашей бригаде чек-лист сдаётся отдельно по каждой ячейке, а вам ячейка ещё не назначена. Обратитесь к бригадиру.",
    noCellOther: "В этой бригаде чек-лист сдаётся по каждой ячейке, а этому лидеру ячейка не назначена — ему нечего сдавать.",
    noLoadT: "Чек-лист не требуется",
    noLoadMine: "Ни одна из ваших ячеек не учитывается в загрузке, и в октябре вы ничего не сдавали — ежедневный чек-лист от вас не требуется, и вы не участвуете в рейтинге. Когда вашу ячейку включат в загрузку, чек-лист появится здесь.",
    noLoadOther: "Ни одна из ячеек этого лидера не учитывается в загрузке, и в октябре он ничего не сдавал — ежедневный чек-лист от него не требуется, и он не участвует в рейтинге.",
    photoFailed: "Фото не загрузилось", failedT: "Не удалось загрузить чек-лист", failedM: "Проверьте интернет и попробуйте ещё раз.", retry: "Повторить",
    runningLbl: "Текущий балл", runningNote: "Учитываются только проверенные задачи · всего {total}",
    submittedOf: "Сдано {n} из {total}", resultLbl: "Итог дня", rawLbl: "Сдано: {raw}%",
    legDone: "Принято", legChecking: "На проверке", legFailed: "Не зачтено", legTodo: "Осталось",
    nextLbl: "Ближайший срок", nextLine: "№{id} · до {time}",
    dayClosedToday: "День закрыт — итог окончательный.",
    nothingT: "За этот день чек-лист не сдан", nothingM: "Ни по одной задаче нет ответа.",
    sheetNote: "Этот день сдан через Google-форму — виден только результат.",
    rehearsalNote: "Тренировочный день — эта сдача через бот не входит в итоги.",
    excludedNote: "Этот день не входит в итоги.", voidedNote: "День сдан не вовремя — считается как 0%.",
    closeDay: "Закрыть день", closeDayNeed: "Чтобы закрыть день, ответьте на все задачи — осталось {n}.",
    closeDayT: "Закрыть день?", closeDayM: "После закрытия ответы изменить нельзя. Фото уйдут на проверку ИИ.",
    closeDayOk: "День закрыт — итог: {score}%",
    gTodo: "Нужно сделать", gRejected: "Отклонено", gFailed: "Не выполнено", gChecking: "На проверке", gDone: "Принято",
    show: "Показать", hide: "Скрыть",
    by: "до {time}", left: "осталось {t}", mins: "{m} мин", hours: "{h} ч {m} мин",
    opens: "откроется в {time}", timeUp: "Время вышло", draft: "Ответ есть — не сдано",
    savedDay: "Ответ сохранён — сдастся при закрытии дня",
    bDraftDayT: "Ответ сохранён", bDraftDayM: "Сдастся, когда вы закроете день. До этого ответ можно начать заново.",
    camRoll: "Снято {k}/{n}", autoAt: "Система проверит в {time}", checking: "ИИ проверяет…",
    accepted: "Принято", byAdmin: "Принято администратором", submittedAt: "Сдано в {time}",
    expired: "Не сдано до {time}", notdone: "Не выполнено", missing: "Ничего не сдано",
    ruledout: "Администратор: не выполнено", autoPassed: "Система подтвердила", autoFailed: "Проверка не пройдена",
    flagged: "ИИ не принял",
    kindCam: "Камера", kindShot: "Фото", kindAuto: "Автоматически", kindNone: "Без фото",
    object: "Возразить", late: "Позднее подтверждение", submit: "Сдать", openChat: "Открыть чат",
    yourTurn: "Ваша очередь",
    dSup: "Возражение — у бригадира", dAdm: "Возражение — у администраторов", dOk: "Возражение принято",
    dNo: "Возражение отклонено", dCancel: "Возражение отменено",
    lSup: "Позднее подтверждение — у бригадира", lAdm: "Позднее подтверждение — у администраторов",
    lOk: "Позднее подтверждение принято", lNo: "Позднее подтверждение отклонено",
    st_open: "Не выполнено", st_draft: "Не сдано", st_pending: "На проверке", st_passed: "Принято",
    st_rejected: "Отклонено", st_expired: "Срок истёк", st_notdone: "Не выполнено", st_missing: "Не сдано",
    st_autopass: "Система подтвердила", st_autofail: "Проверка не пройдена", st_ruledout: "Администратор: не выполнено",
    bPendingT: "ИИ проверяет фото", bPendingM: "Обычно несколько минут. Результат появится здесь сам.",
    bPassedT: "Задача принята", bPassedAdminT: "Администратор засчитал задачу",
    bRejectedT: "ИИ не принял фото", bRejectedM: "Балл за задачу не начисляется. Если решение неверное — возразите.",
    bAutoFailT: "Автоматическая проверка не пройдена", bAutoFailM: "Если проверка ошиблась — возразите.",
    bAutoPassT: "Автоматическая проверка пройдена",
    bExpiredT: "Срок истёк", bExpiredM: "Не сдано до {time}.",
    bNotdoneT: "Сдано как «не выполнено»", bMissingT: "Задача не сдана",
    bRuledoutT: "Администратор посчитал задачу невыполненной",
    bDraftT: "Ответ сохранён, но ещё не сдан",
    bDraftM: "Пока задача не сдана, балл не считается. Когда срок выйдет, система сдаст её сама.",
    bNotStartedT: "Задача откроется в {time}", bNotStartedM: "Фото, снятое раньше, будет отклонено.",
    bTimeUpT: "Время вышло", bTimeUpM: "После {time} задачу нельзя сдать обычным путём — только позднее подтверждение.",
    ruleDeadline: "Сдать", ruleWindow: "Время фото", ruleWindowV: "{from}–{to}",
    ruleDay: "На фото должна быть сегодняшняя дата", ruleTime: "Время на фото: {from}–{to}", ruleNone: "Дата не проверяется",
    ruleWeight: "Доля", rulePhotos: "Фото", rulePhotosV: "не меньше {n}",
    howTo: "Как выполнить", examples: "Образец", more: "Подробнее", less: "Свернуть",
    q: "Задача выполнена?", yes: "Выполнено", no: "Не выполнено",
    photosLbl: "Фото-подтверждения", photosNeed: "Не меньше {n}, не больше {max}",
    dropLabel: "Выбрать фото", dropActive: "Отпустите", dropBusy: "Загрузка…",
    dropHint: "На компьютере скриншот можно вставить через Ctrl+V.",
    notImage: "Можно загрузить только фото", removePhoto: "Убрать фото", tooMany: "Не больше {max} фото",
    reasonLbl: "Почему не выполнено?", reasonPh: "Коротко — прочтут бригадир и администратор",
    camT: "Эта задача снимается камерой в приложении",
    camM: "Загрузить фото из галереи нельзя — время съёмки ставит система.",
    camOpen: "Открыть камеру", camMore: "Продолжить съёмку", camHave: "Снято: {k} / {n}",
    camReady: "Фото готовы — теперь сдайте", noProof: "Для этой задачи фото не нужно.",
    submitT: "Сдать задачу?",
    submitM: "После сдачи ответ изменить нельзя. ИИ обычно проверяет фото за несколько минут — результат появится здесь.",
    submitNoM: "Задача будет сдана как «не выполнено» — балл за неё не начисляется. Изменить потом нельзя.",
    submitOk: "Сдано — ИИ проверяет", submitNoOk: "Сдано", saveOk: "Сохранено",
    save: "Сохранить", cancel: "Отмена", close: "Закрыть",
    restart: "Начать заново", restartT: "Удалить ответ?",
    restartM: "Ответ и фото по этой задаче удалятся — потом сдадите заново.", restartOk: "Ответ удалён",
    answerLbl: "Ответ", evidence: "Подтверждение", reasonShown: "Причина",
    objT: "Возражение",
    objIntro: "Если решение неверное, напишите почему. Бригадир прочтёт: отклонит или передаст администраторам. Балл вернётся только после решения администратора.",
    objIntroAuto: "Если проверка ошиблась (например, данные были внесены вовремя), напишите почему. Прочтёт бригадир, затем решат администраторы.",
    objPh: "Например: время на фото хорошо видно", objPhAuto: "Например: план был внесён в 9:40",
    objEmpty: "Ваше возражение откроет чат с бригадиром и администраторами.",
    objSent: "Возражение отправлено — его рассмотрит бригадир",
    lateT: "Позднее подтверждение",
    lateIntro: "Срок прошёл, поэтому это подтверждение само балл не даёт. Вашу причину прочтут бригадир, затем администратор — если примут, задача засчитается полностью.",
    lateOpen: "Отправить позднее подтверждение", lateReason: "Почему опоздали?", lateReasonPh: "Например: разрядился телефон",
    lateCam: "Снять в приложении", lateShot: "Снято камерой: {n}", lateSend: "Отправить",
    lateOk: "Позднее подтверждение отправлено — его рассмотрит бригадир", latePhotosLbl: "Фото", lateNeed: "Нужно хотя бы одно фото",
    autoT: "Эту задачу система проверяет сама",
    autoM: "В {time} система прочитает данные — фото присылать не нужно. Сделайте работу на её странице вовремя.",
    autoLive: "Сейчас", autoLiveErr: "Не удалось прочитать текущее состояние",
    lvPlan: "Позиции с планом: {a} / {b}", lvUntyped: "Не внесено количество людей: {codes}",
    lvPeopleOk: "Количество людей внесено", lvPct: "Выполнение: {pct}% (цель {target}%)",
    lvConcerns: "Записано обеспокоенностей сегодня: {n}", lvNoSap: "У ячейки нет кода SAP — исправят администраторы",
    adminT: "Администратор", admReopen: "Открыть заново", admEmpty: "Очистить",
    admReopenT: "Открыть задачу заново?",
    admReopenM: "Лидер сможет сдать её заново. Заключение ИИ удалится, оценка дня пересчитается.",
    admEmptyT: "Очистить задачу?", admEmptyM: "Ответ и фото удалятся, задача откроется заново.",
    admOk: "Задача открыта заново", admEmptyOk: "Задача очищена",
    tPassed: "№{id} принята", tRejected: "№{id} отклонена — можно возразить",
    missedLine: "Не сдано до {time}.",
    e_time_up: "Время вышло — теперь можно только позднее подтверждение.", e_locked: "Эта задача уже сдана.",
    e_day_closed: "День закрыт.", e_camera_task: "Эта задача снимается только камерой в приложении.",
    e_auto_task: "Эту задачу система проверяет сама.", e_need_photos: "Недостаточно фото.",
    e_too_many_photos: "Слишком много фото.", e_reason_required: "Напишите причину (не меньше 3 символов).",
    e_invalid_image: "Этот файл не фото или его не удалось прочитать.", e_too_large: "Фото слишком большое (до 10 МБ).",
    e_relay_failed: "Не удалось сохранить фото — попробуйте ещё раз.", e_late_gone: "Срок для позднего подтверждения истёк.",
    e_incomplete: "Задача ещё не заполнена.", e_pick_cell: "Выберите ячейку.",
    e_no_load: "Чек-лист от вас не требуется — ваши ячейки не учитываются в загрузке.",
    e_generic: "Не удалось сохранить — попробуйте ещё раз.",
  },
  en: {
    mine: "My checklist", readOnly: "View only — the leader submits their own tasks.",
    pickT: "Pick a leader",
    pickM: "Choose a leader in the «Leader» filter above to see their day.",
    pickHere: "Choose a leader from the list below to see their day.",
    noCellT: "No cell assigned",
    noCellMine: "Your unit files the checklist separately for each cell, and no cell is assigned to you yet. Ask your brigadir.",
    noCellOther: "This unit files the checklist per cell, and this leader has no cell assigned — there is nothing for them to file.",
    noLoadT: "No checklist required",
    noLoadMine: "None of your cells counts in the workload and you filed nothing in October — no daily checklist is asked of you and you are not in the ranking. Once your cell is added to the workload, the checklist appears here.",
    noLoadOther: "None of this leader's cells counts in the workload and they filed nothing in October — no daily checklist is asked of them and they are not in the ranking.",
    photoFailed: "Photo failed to load", failedT: "Could not load the checklist", failedM: "Check the connection and try again.", retry: "Try again",
    runningLbl: "Score so far", runningNote: "Only checked tasks count · {total} in total",
    submittedOf: "{n} of {total} submitted", resultLbl: "Day result", rawLbl: "Submitted: {raw}%",
    legDone: "Accepted", legChecking: "Being checked", legFailed: "Not counted", legTodo: "Left",
    nextLbl: "Next deadline", nextLine: "№{id} · by {time}",
    dayClosedToday: "The day is closed — the result is final.",
    nothingT: "No checklist was filed this day", nothingM: "No task has an answer.",
    sheetNote: "This day was filed through the Google form — only the result is shown.",
    rehearsalNote: "Practice day — this bot filing does not count.",
    excludedNote: "This day is not counted in the results.", voidedNote: "Filed late — the day counts as 0%.",
    closeDay: "Close the day", closeDayNeed: "Answer every task to close the day — {n} left.",
    closeDayT: "Close the day?", closeDayM: "Answers can't be changed once the day is closed. Photos go to the AI check.",
    closeDayOk: "Day closed — result: {score}%",
    gTodo: "To do", gRejected: "Rejected", gFailed: "Not done", gChecking: "Being checked", gDone: "Accepted",
    show: "Show", hide: "Hide",
    by: "by {time}", left: "{t} left", mins: "{m} min", hours: "{h} h {m} min",
    opens: "opens at {time}", timeUp: "Time is up", draft: "Answered — not submitted",
    savedDay: "Answer saved — submitted when the day is closed",
    bDraftDayT: "Answer saved", bDraftDayM: "It is submitted when you close the day. Until then you can start it over.",
    camRoll: "Shot {k}/{n}", autoAt: "Checked by the platform at {time}", checking: "The AI is checking…",
    accepted: "Accepted", byAdmin: "Accepted by an admin", submittedAt: "Submitted at {time}",
    expired: "Not submitted by {time}", notdone: "Not done", missing: "Nothing was filed",
    ruledout: "Admin: not done", autoPassed: "Confirmed by the platform", autoFailed: "Failed the check",
    flagged: "Rejected by the AI",
    kindCam: "Camera", kindShot: "Photo", kindAuto: "Automatic", kindNone: "No photo",
    object: "Object", late: "Late proof", submit: "Submit", openChat: "Open the chat",
    yourTurn: "Your turn",
    dSup: "Objection — with the brigadir", dAdm: "Objection — with the admins", dOk: "Objection upheld",
    dNo: "Objection refused", dCancel: "Objection cancelled",
    lSup: "Late proof — with the brigadir", lAdm: "Late proof — with the admins",
    lOk: "Late proof accepted", lNo: "Late proof refused",
    st_open: "Not done yet", st_draft: "Not submitted", st_pending: "Being checked", st_passed: "Accepted",
    st_rejected: "Rejected", st_expired: "Time ran out", st_notdone: "Not done", st_missing: "Not filed",
    st_autopass: "Confirmed by the platform", st_autofail: "Failed the check", st_ruledout: "Admin: not done",
    bPendingT: "The AI is checking the photos", bPendingM: "Usually a few minutes. The result appears here by itself.",
    bPassedT: "Task accepted", bPassedAdminT: "An admin counted this task as done",
    bRejectedT: "The AI did not accept the photo", bRejectedM: "This task earns no points. If the ruling is wrong, object.",
    bAutoFailT: "Failed the automatic check", bAutoFailM: "If the check got it wrong, object.",
    bAutoPassT: "Passed the automatic check",
    bExpiredT: "The deadline passed", bExpiredM: "Not submitted by {time}.",
    bNotdoneT: "Submitted as «not done»", bMissingT: "This task was not filed",
    bRuledoutT: "An admin counted this task as not done",
    bDraftT: "Answer saved, but not submitted yet",
    bDraftM: "It scores nothing until you submit it. When its time runs out, the platform submits it for you.",
    bNotStartedT: "This task opens at {time}", bNotStartedM: "A photo taken before then will be rejected.",
    bTimeUpT: "Time is up", bTimeUpM: "After {time} the task can't be submitted the normal way — only as a late proof.",
    ruleDeadline: "Submit", ruleWindow: "Photo time", ruleWindowV: "{from}–{to}",
    ruleDay: "The photo must show today's date", ruleTime: "Clock on the photo: {from}–{to}", ruleNone: "Date not checked",
    ruleWeight: "Weight", rulePhotos: "Photos", rulePhotosV: "at least {n}",
    howTo: "How to do it", examples: "Example", more: "More", less: "Less",
    q: "Was the task done?", yes: "Done", no: "Not done",
    photosLbl: "Proof photos", photosNeed: "At least {n}, at most {max}",
    dropLabel: "Choose photos", dropActive: "Drop them here", dropBusy: "Uploading…",
    dropHint: "On a computer you can also paste a screenshot with Ctrl+V.",
    notImage: "Only photos can be uploaded", removePhoto: "Remove photo", tooMany: "At most {max} photos",
    reasonLbl: "Why wasn't it done?", reasonPh: "Keep it short — the brigadir and admin read it",
    camT: "This task is shot with the in-app camera",
    camM: "Photos can't be uploaded from the gallery — the platform stamps the time they were taken.",
    camOpen: "Open the camera", camMore: "Continue shooting", camHave: "Shot: {k} / {n}",
    camReady: "Photos are ready — submit them now", noProof: "No photo is needed for this task.",
    submitT: "Submit this task?",
    submitM: "Once submitted, the answer can't be changed. The AI usually checks the photos within a few minutes — the result appears here.",
    submitNoM: "The task will be submitted as «not done» and earns no points. It can't be changed afterwards.",
    submitOk: "Submitted — the AI is checking", submitNoOk: "Submitted", saveOk: "Saved",
    save: "Save", cancel: "Cancel", close: "Close",
    restart: "Start over", restartT: "Delete the answer?",
    restartM: "The answer and photos for this task will be deleted — you'll submit it again.", restartOk: "Answer deleted",
    answerLbl: "Answer", evidence: "Proof", reasonShown: "Reason",
    objT: "Objection",
    objIntro: "If the ruling is wrong, write why. Your brigadir reads it: refuses it or passes it to the admins. The points come back only on an admin's ruling.",
    objIntroAuto: "If the check got it wrong (for example, the data was entered on time), write why. Your brigadir reads it, then the admins decide.",
    objPh: "For example: the time is clearly visible on the photo", objPhAuto: "For example: the plan was entered at 9:40",
    objEmpty: "Your objection opens a chat with your brigadir and the admins.",
    objSent: "Objection sent — your brigadir will review it",
    lateT: "Late proof",
    lateIntro: "The deadline has passed, so this proof earns nothing by itself. Your brigadir and then an admin read your reason — if they accept it, the task counts in full.",
    lateOpen: "Send a late proof", lateReason: "Why was it late?", lateReasonPh: "For example: my phone died",
    lateCam: "Shoot in the app", lateShot: "Shot with the camera: {n}", lateSend: "Send",
    lateOk: "Late proof sent — your brigadir will review it", latePhotosLbl: "Photos", lateNeed: "At least one photo is needed",
    autoT: "The platform checks this task itself",
    autoM: "At {time} the platform reads the data — no photo is needed. Do the work on its own page in time.",
    autoLive: "Right now", autoLiveErr: "Could not read the current state",
    lvPlan: "Positions with a plan: {a} / {b}", lvUntyped: "Headcount missing: {codes}",
    lvPeopleOk: "Headcount entered", lvPct: "Fulfilment: {pct}% (target {target}%)",
    lvConcerns: "Concerns written today: {n}", lvNoSap: "The cell has no SAP code — the admins will fix it",
    adminT: "Admin", admReopen: "Reopen", admEmpty: "Empty",
    admReopenT: "Reopen this task?",
    admReopenM: "The leader can submit it again. The AI verdict is removed and the day's score is recalculated.",
    admEmptyT: "Empty this task?", admEmptyM: "The answer and photos are deleted and the task is reopened.",
    admOk: "Task reopened", admEmptyOk: "Task emptied",
    tPassed: "№{id} accepted", tRejected: "№{id} rejected — you can object",
    missedLine: "Not submitted by {time}.",
    e_time_up: "Time is up — only a late proof can be sent now.", e_locked: "This task has already been submitted.",
    e_day_closed: "The day is closed.", e_camera_task: "This task can only be shot with the in-app camera.",
    e_auto_task: "The platform checks this task itself.", e_need_photos: "Not enough photos.",
    e_too_many_photos: "Too many photos.", e_reason_required: "Write a reason (at least 3 characters).",
    e_invalid_image: "This file is not a photo or could not be read.", e_too_large: "The photo is too large (up to 10 MB).",
    e_relay_failed: "The photo could not be saved — try again.", e_late_gone: "The time for a late proof has passed.",
    e_incomplete: "The task isn't complete yet.", e_pick_cell: "Choose a cell.",
    e_no_load: "No checklist is asked of you — your cells do not count in the workload.",
    e_generic: "Could not save — try again.",
  },
};

export function useClT() {
  const { lang } = useLang();
  return CL_T[lang] || CL_T.ru;
}

export const put = (s, p) => Object.entries(p || {}).reduce(
  (a, [k, v]) => a.replaceAll(`{${k}}`, v == null ? "" : String(v)), String(s || ""));

/** The server's refusal code (`detail`) in the reader's words, never raw. */
export function errText(err, T) {
  const raw = err?.response?.data?.detail_raw ?? err?.response?.data?.detail;
  const code = typeof raw === "string" ? raw : "";
  return T[`e_${code}`] || T.e_generic;
}
